// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Code generated by Project Forge, see https://projectforge.dev for details. -->

//line views/vfile/Detail.html:2
package vfile

//line views/vfile/Detail.html:2
import (
	"path/filepath"

	"github.com/kyleu/projectforge/app"
	"github.com/kyleu/projectforge/app/controller/cutil"
)

//line views/vfile/Detail.html:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vfile/Detail.html:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vfile/Detail.html:9
func StreamDetail(qw422016 *qt422016.Writer, path []string, b []byte, urlPrefix string, as *app.State, ps *cutil.PageState) {
//line views/vfile/Detail.html:9
	qw422016.N().S(`
  <div class="card">
    <h3>`)
//line views/vfile/Detail.html:11
	for idx, p := range path {
//line views/vfile/Detail.html:11
		qw422016.N().S(`/<a href="`)
//line views/vfile/Detail.html:11
		qw422016.E().S(urlPrefix)
//line views/vfile/Detail.html:11
		qw422016.N().S(`/`)
//line views/vfile/Detail.html:11
		qw422016.E().S(filepath.Join(path[:idx+1]...))
//line views/vfile/Detail.html:11
		qw422016.N().S(`">`)
//line views/vfile/Detail.html:11
		qw422016.E().S(p)
//line views/vfile/Detail.html:11
		qw422016.N().S(`</a>`)
//line views/vfile/Detail.html:11
	}
//line views/vfile/Detail.html:11
	qw422016.N().S(`</h3>
    <div class="mt">
`)
//line views/vfile/Detail.html:14
	out, _ := cutil.FormatFilename(string(b), path[len(path)-1])

//line views/vfile/Detail.html:15
	qw422016.N().S(`      `)
//line views/vfile/Detail.html:16
	qw422016.N().S(out)
//line views/vfile/Detail.html:16
	qw422016.N().S(`
    </div>
  </div>
`)
//line views/vfile/Detail.html:19
}

//line views/vfile/Detail.html:19
func WriteDetail(qq422016 qtio422016.Writer, path []string, b []byte, urlPrefix string, as *app.State, ps *cutil.PageState) {
//line views/vfile/Detail.html:19
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vfile/Detail.html:19
	StreamDetail(qw422016, path, b, urlPrefix, as, ps)
//line views/vfile/Detail.html:19
	qt422016.ReleaseWriter(qw422016)
//line views/vfile/Detail.html:19
}

//line views/vfile/Detail.html:19
func Detail(path []string, b []byte, urlPrefix string, as *app.State, ps *cutil.PageState) string {
//line views/vfile/Detail.html:19
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vfile/Detail.html:19
	WriteDetail(qb422016, path, b, urlPrefix, as, ps)
//line views/vfile/Detail.html:19
	qs422016 := string(qb422016.B)
//line views/vfile/Detail.html:19
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vfile/Detail.html:19
	return qs422016
//line views/vfile/Detail.html:19
}
