// Code generated by qtc from "Pagination.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/components/Pagination.html:1
package components

//line views/components/Pagination.html:1
import "github.com/valyala/fasthttp"

//line views/components/Pagination.html:2
import "github.com/kyleu/projectforge/app/filter"

//line views/components/Pagination.html:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/components/Pagination.html:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/components/Pagination.html:4
func StreamPagination(qw422016 *qt422016.Writer, section string, count int, params *filter.Params, u *fasthttp.URI) {
//line views/components/Pagination.html:5
	if params != nil {
//line views/components/Pagination.html:6
		if params.HasNextPage(count) {
//line views/components/Pagination.html:6
			qw422016.N().S(`<div class="right"><a href="?`)
//line views/components/Pagination.html:8
			qw422016.E().S(params.NextPage().ToQueryString(u))
//line views/components/Pagination.html:8
			qw422016.N().S(`">Next page</a></div>`)
//line views/components/Pagination.html:10
		}
//line views/components/Pagination.html:11
		if params.HasPreviousPage() {
//line views/components/Pagination.html:11
			qw422016.N().S(`<div class="left"><a href="?`)
//line views/components/Pagination.html:13
			qw422016.E().S(params.PreviousPage().ToQueryString(u))
//line views/components/Pagination.html:13
			qw422016.N().S(`">Previous page</a></div>`)
//line views/components/Pagination.html:15
		}
//line views/components/Pagination.html:16
	}
//line views/components/Pagination.html:17
}

//line views/components/Pagination.html:17
func WritePagination(qq422016 qtio422016.Writer, section string, count int, params *filter.Params, u *fasthttp.URI) {
//line views/components/Pagination.html:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/Pagination.html:17
	StreamPagination(qw422016, section, count, params, u)
//line views/components/Pagination.html:17
	qt422016.ReleaseWriter(qw422016)
//line views/components/Pagination.html:17
}

//line views/components/Pagination.html:17
func Pagination(section string, count int, params *filter.Params, u *fasthttp.URI) string {
//line views/components/Pagination.html:17
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/Pagination.html:17
	WritePagination(qb422016, section, count, params, u)
//line views/components/Pagination.html:17
	qs422016 := string(qb422016.B)
//line views/components/Pagination.html:17
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/Pagination.html:17
	return qs422016
//line views/components/Pagination.html:17
}
