// Code generated by qtc from "DetailMetadata.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vproject/DetailMetadata.html:1
package vproject

//line views/vproject/DetailMetadata.html:1
import (
	"projectforge.dev/projectforge/app"
	"projectforge.dev/projectforge/app/controller/cutil"
	"projectforge.dev/projectforge/app/project"
)

//line views/vproject/DetailMetadata.html:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vproject/DetailMetadata.html:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vproject/DetailMetadata.html:7
func StreamDetailMetadata(qw422016 *qt422016.Writer, info *project.Info, as *app.State, ps *cutil.PageState) {
//line views/vproject/DetailMetadata.html:7
	qw422016.N().S(`
  <div class="overflow full-width">
    <table class="min-200 full-width">
      <tbody>
        <tr class="shrink">
          <th class="shrink">Organization</th>
          <td>`)
//line views/vproject/DetailMetadata.html:13
	qw422016.E().S(info.Org)
//line views/vproject/DetailMetadata.html:13
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th>Author ID</th>
          <td>`)
//line views/vproject/DetailMetadata.html:17
	qw422016.E().S(info.AuthorID)
//line views/vproject/DetailMetadata.html:17
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th>Author</th>
          <td>`)
//line views/vproject/DetailMetadata.html:21
	qw422016.E().S(info.AuthorName)
//line views/vproject/DetailMetadata.html:21
	qw422016.N().S(` &lt;<a href="mailto:`)
//line views/vproject/DetailMetadata.html:21
	qw422016.E().S(info.AuthorEmail)
//line views/vproject/DetailMetadata.html:21
	qw422016.N().S(`">`)
//line views/vproject/DetailMetadata.html:21
	qw422016.E().S(info.AuthorEmail)
//line views/vproject/DetailMetadata.html:21
	qw422016.N().S(`</a>&gt;</td>
        </tr>
        <tr>
          <th>Team</th>
          <td>`)
//line views/vproject/DetailMetadata.html:25
	qw422016.E().S(info.Team)
//line views/vproject/DetailMetadata.html:25
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th>License</th>
          <td>`)
//line views/vproject/DetailMetadata.html:29
	qw422016.E().S(info.License)
//line views/vproject/DetailMetadata.html:29
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th>Homepage</th>
          <td>`)
//line views/vproject/DetailMetadata.html:33
	qw422016.E().S(info.Homepage)
//line views/vproject/DetailMetadata.html:33
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th>Source Code</th>
          <td>`)
//line views/vproject/DetailMetadata.html:37
	qw422016.E().S(info.Sourcecode)
//line views/vproject/DetailMetadata.html:37
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th>Summary</th>
          <td>`)
//line views/vproject/DetailMetadata.html:41
	qw422016.E().S(info.Summary)
//line views/vproject/DetailMetadata.html:41
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th>Description</th>
          <td>`)
//line views/vproject/DetailMetadata.html:45
	qw422016.E().S(info.Description)
//line views/vproject/DetailMetadata.html:45
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th>CI</th>
          <td>`)
//line views/vproject/DetailMetadata.html:49
	qw422016.E().S(info.CI)
//line views/vproject/DetailMetadata.html:49
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th>Homebrew</th>
          <td>`)
//line views/vproject/DetailMetadata.html:53
	qw422016.E().S(info.Homebrew)
//line views/vproject/DetailMetadata.html:53
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th>Bundle</th>
          <td>`)
//line views/vproject/DetailMetadata.html:57
	qw422016.E().S(info.Bundle)
//line views/vproject/DetailMetadata.html:57
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th>Signing Identity</th>
          <td>`)
//line views/vproject/DetailMetadata.html:61
	qw422016.E().S(info.SigningIdentity)
//line views/vproject/DetailMetadata.html:61
	qw422016.N().S(`</td>
        </tr>
`)
//line views/vproject/DetailMetadata.html:63
	if info.NotarizeEmail != "" {
//line views/vproject/DetailMetadata.html:63
		qw422016.N().S(`        <tr>
          <th>Notarize Email</th>
          <td>`)
//line views/vproject/DetailMetadata.html:66
		qw422016.E().S(info.NotarizeEmail)
//line views/vproject/DetailMetadata.html:66
		qw422016.N().S(` &lt;<a href="mailto:`)
//line views/vproject/DetailMetadata.html:66
		qw422016.E().S(info.NotarizeEmail)
//line views/vproject/DetailMetadata.html:66
		qw422016.N().S(`">`)
//line views/vproject/DetailMetadata.html:66
		qw422016.E().S(info.NotarizeEmail)
//line views/vproject/DetailMetadata.html:66
		qw422016.N().S(`</a>&gt;</td>
        </tr>
`)
//line views/vproject/DetailMetadata.html:68
	}
//line views/vproject/DetailMetadata.html:69
	if info.DatabaseEngine != "" {
//line views/vproject/DetailMetadata.html:69
		qw422016.N().S(`        <tr>
          <th>Database Engine</th>
          <td>`)
//line views/vproject/DetailMetadata.html:72
		qw422016.E().S(info.DatabaseEngine)
//line views/vproject/DetailMetadata.html:72
		qw422016.N().S(`</td>
        </tr>
`)
//line views/vproject/DetailMetadata.html:74
	}
//line views/vproject/DetailMetadata.html:74
	qw422016.N().S(`        <tr>
          <th>Slack Webhook</th>
          <td>`)
//line views/vproject/DetailMetadata.html:77
	qw422016.E().S(info.Slack)
//line views/vproject/DetailMetadata.html:77
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th>Channels</th>
          <td>
`)
//line views/vproject/DetailMetadata.html:82
	for _, x := range info.Channels {
//line views/vproject/DetailMetadata.html:82
		qw422016.N().S(`            <div>`)
//line views/vproject/DetailMetadata.html:83
		qw422016.E().S(x)
//line views/vproject/DetailMetadata.html:83
		qw422016.N().S(`</div>
`)
//line views/vproject/DetailMetadata.html:84
	}
//line views/vproject/DetailMetadata.html:84
	qw422016.N().S(`          </td>
        </tr>
        <tr>
          <th>Java Package</th>
          <td>`)
//line views/vproject/DetailMetadata.html:89
	qw422016.E().S(info.JavaPackage)
//line views/vproject/DetailMetadata.html:89
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th>Go Binary</th>
          <td>`)
//line views/vproject/DetailMetadata.html:93
	qw422016.E().S(info.GoBinary)
//line views/vproject/DetailMetadata.html:93
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th>Go Version</th>
          <td>`)
//line views/vproject/DetailMetadata.html:97
	qw422016.E().S(info.GoVersion)
//line views/vproject/DetailMetadata.html:97
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th>Extra Files</th>
          <td>
`)
//line views/vproject/DetailMetadata.html:102
	if len(info.ExtraFiles) == 0 {
//line views/vproject/DetailMetadata.html:102
		qw422016.N().S(`            <em>none</em>
`)
//line views/vproject/DetailMetadata.html:104
	} else {
//line views/vproject/DetailMetadata.html:104
		qw422016.N().S(`            <ul>
`)
//line views/vproject/DetailMetadata.html:106
		for _, x := range info.ExtraFiles {
//line views/vproject/DetailMetadata.html:106
			qw422016.N().S(`              <li>`)
//line views/vproject/DetailMetadata.html:107
			qw422016.E().S(x)
//line views/vproject/DetailMetadata.html:107
			qw422016.N().S(`</li>
`)
//line views/vproject/DetailMetadata.html:108
		}
//line views/vproject/DetailMetadata.html:108
		qw422016.N().S(`            </ul>
`)
//line views/vproject/DetailMetadata.html:110
	}
//line views/vproject/DetailMetadata.html:110
	qw422016.N().S(`          </td>
        </tr>
        <tr>
          <th>Deployments</th>
          <td>
`)
//line views/vproject/DetailMetadata.html:116
	if len(info.Deployments) == 0 {
//line views/vproject/DetailMetadata.html:116
		qw422016.N().S(`            <em>none</em>
`)
//line views/vproject/DetailMetadata.html:118
	} else {
//line views/vproject/DetailMetadata.html:118
		qw422016.N().S(`            <ul>
`)
//line views/vproject/DetailMetadata.html:120
		for _, x := range info.Deployments {
//line views/vproject/DetailMetadata.html:120
			qw422016.N().S(`              <li>`)
//line views/vproject/DetailMetadata.html:121
			qw422016.E().S(x)
//line views/vproject/DetailMetadata.html:121
			qw422016.N().S(`</li>
`)
//line views/vproject/DetailMetadata.html:122
		}
//line views/vproject/DetailMetadata.html:122
		qw422016.N().S(`            </ul>
`)
//line views/vproject/DetailMetadata.html:124
	}
//line views/vproject/DetailMetadata.html:124
	qw422016.N().S(`          </td>
        </tr>
        <tr>
          <th>Env Vars</th>
          <td>
`)
//line views/vproject/DetailMetadata.html:130
	if len(info.EnvVars) == 0 {
//line views/vproject/DetailMetadata.html:130
		qw422016.N().S(`            <em>none</em>
`)
//line views/vproject/DetailMetadata.html:132
	} else {
//line views/vproject/DetailMetadata.html:132
		qw422016.N().S(`            <ul>
`)
//line views/vproject/DetailMetadata.html:134
		for _, x := range info.EnvVars {
//line views/vproject/DetailMetadata.html:134
			qw422016.N().S(`              <li>`)
//line views/vproject/DetailMetadata.html:135
			qw422016.E().S(x)
//line views/vproject/DetailMetadata.html:135
			qw422016.N().S(`</li>
`)
//line views/vproject/DetailMetadata.html:136
		}
//line views/vproject/DetailMetadata.html:136
		qw422016.N().S(`            </ul>
`)
//line views/vproject/DetailMetadata.html:138
	}
//line views/vproject/DetailMetadata.html:138
	qw422016.N().S(`          </td>
        </tr>
        <tr>
          <th>Config Vars</th>
          <td>
`)
//line views/vproject/DetailMetadata.html:144
	if len(info.ConfigVars) == 0 {
//line views/vproject/DetailMetadata.html:144
		qw422016.N().S(`            <em>no config vars</em>
`)
//line views/vproject/DetailMetadata.html:146
	} else {
//line views/vproject/DetailMetadata.html:146
		qw422016.N().S(`            <div class="overflow full-width">
              <table>
                <thead>
                  <tr>
                    <th>Key</th>
                    <th>Type</th>
                    <th>Description</th>
                  </tr>
                </thead>
                <tbody>
`)
//line views/vproject/DetailMetadata.html:157
		for _, cv := range info.ConfigVars {
//line views/vproject/DetailMetadata.html:157
			qw422016.N().S(`                  <tr>
                    <td><code>`)
//line views/vproject/DetailMetadata.html:159
			qw422016.E().S(cv.Key)
//line views/vproject/DetailMetadata.html:159
			qw422016.N().S(`</code></td>
                    <td>`)
//line views/vproject/DetailMetadata.html:160
			qw422016.E().S(cv.Type)
//line views/vproject/DetailMetadata.html:160
			qw422016.N().S(`</td>
                    <td>`)
//line views/vproject/DetailMetadata.html:161
			qw422016.E().S(cv.Description)
//line views/vproject/DetailMetadata.html:161
			qw422016.N().S(`</td>
                  </tr>
`)
//line views/vproject/DetailMetadata.html:163
		}
//line views/vproject/DetailMetadata.html:163
		qw422016.N().S(`                </tbody>
              </table>
            </div>
`)
//line views/vproject/DetailMetadata.html:167
	}
//line views/vproject/DetailMetadata.html:167
	qw422016.N().S(`          </td>
        </tr>
        <tr>
          <th>Documentation</th>
          <td>
`)
//line views/vproject/DetailMetadata.html:173
	if len(info.Docs) == 0 {
//line views/vproject/DetailMetadata.html:173
		qw422016.N().S(`            <em>none</em>
`)
//line views/vproject/DetailMetadata.html:175
	} else {
//line views/vproject/DetailMetadata.html:175
		qw422016.N().S(`            <div class="overflow full-width">
              <table>
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Provider</th>
                    <th>URL</th>
                  </tr>
                </thead>
                <tbody>
`)
//line views/vproject/DetailMetadata.html:186
		for _, d := range info.Docs {
//line views/vproject/DetailMetadata.html:186
			qw422016.N().S(`                  <tr>
                    <td><code>`)
//line views/vproject/DetailMetadata.html:188
			qw422016.E().S(d.Name)
//line views/vproject/DetailMetadata.html:188
			qw422016.N().S(`</code></td>
                    <td>`)
//line views/vproject/DetailMetadata.html:189
			qw422016.E().S(d.Provider)
//line views/vproject/DetailMetadata.html:189
			qw422016.N().S(`</td>
                    <td>`)
//line views/vproject/DetailMetadata.html:190
			qw422016.E().S(d.URL)
//line views/vproject/DetailMetadata.html:190
			qw422016.N().S(`</td>
                  </tr>
`)
//line views/vproject/DetailMetadata.html:192
		}
//line views/vproject/DetailMetadata.html:192
		qw422016.N().S(`                </tbody>
              </table>
            </div>
`)
//line views/vproject/DetailMetadata.html:196
	}
//line views/vproject/DetailMetadata.html:196
	qw422016.N().S(`          </td>
        </tr>
        <tr>
          <th>Acronyms</th>
          <td>
`)
//line views/vproject/DetailMetadata.html:202
	if len(info.Acronyms) == 0 {
//line views/vproject/DetailMetadata.html:202
		qw422016.N().S(`            <em>none</em>
`)
//line views/vproject/DetailMetadata.html:204
	} else {
//line views/vproject/DetailMetadata.html:204
		qw422016.N().S(`            <ul>
`)
//line views/vproject/DetailMetadata.html:206
		for _, x := range info.Acronyms {
//line views/vproject/DetailMetadata.html:206
			qw422016.N().S(`              <li><code>`)
//line views/vproject/DetailMetadata.html:207
			qw422016.E().S(x)
//line views/vproject/DetailMetadata.html:207
			qw422016.N().S(`</code></li>
`)
//line views/vproject/DetailMetadata.html:208
		}
//line views/vproject/DetailMetadata.html:208
		qw422016.N().S(`            </ul>
`)
//line views/vproject/DetailMetadata.html:210
	}
//line views/vproject/DetailMetadata.html:210
	qw422016.N().S(`          </td>
        </tr>
`)
//line views/vproject/DetailMetadata.html:213
	if len(info.ModuleDefs) > 0 {
//line views/vproject/DetailMetadata.html:213
		qw422016.N().S(`        <tr>
          <th>Module Definitions</th>
          <td>
`)
//line views/vproject/DetailMetadata.html:217
		for _, x := range info.ModuleDefs {
//line views/vproject/DetailMetadata.html:217
			qw422016.N().S(`            <a href="/m/`)
//line views/vproject/DetailMetadata.html:218
			qw422016.E().S(x.Key)
//line views/vproject/DetailMetadata.html:218
			qw422016.N().S(`">`)
//line views/vproject/DetailMetadata.html:218
			qw422016.E().S(x.Key)
//line views/vproject/DetailMetadata.html:218
			qw422016.N().S(`</a> <em>(`)
//line views/vproject/DetailMetadata.html:218
			qw422016.E().S(x.Path)
//line views/vproject/DetailMetadata.html:218
			qw422016.N().S(`)</em><br />
`)
//line views/vproject/DetailMetadata.html:219
		}
//line views/vproject/DetailMetadata.html:219
		qw422016.N().S(`          </td>
        </tr>
`)
//line views/vproject/DetailMetadata.html:222
	}
//line views/vproject/DetailMetadata.html:222
	qw422016.N().S(`      </tbody>
    </table>
  </div>
`)
//line views/vproject/DetailMetadata.html:226
}

//line views/vproject/DetailMetadata.html:226
func WriteDetailMetadata(qq422016 qtio422016.Writer, info *project.Info, as *app.State, ps *cutil.PageState) {
//line views/vproject/DetailMetadata.html:226
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vproject/DetailMetadata.html:226
	StreamDetailMetadata(qw422016, info, as, ps)
//line views/vproject/DetailMetadata.html:226
	qt422016.ReleaseWriter(qw422016)
//line views/vproject/DetailMetadata.html:226
}

//line views/vproject/DetailMetadata.html:226
func DetailMetadata(info *project.Info, as *app.State, ps *cutil.PageState) string {
//line views/vproject/DetailMetadata.html:226
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vproject/DetailMetadata.html:226
	WriteDetailMetadata(qb422016, info, as, ps)
//line views/vproject/DetailMetadata.html:226
	qs422016 := string(qb422016.B)
//line views/vproject/DetailMetadata.html:226
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vproject/DetailMetadata.html:226
	return qs422016
//line views/vproject/DetailMetadata.html:226
}
