// Code generated by qtc from "List.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vproject/List.html:1
package vproject

//line views/vproject/List.html:1
import (
	"projectforge.dev/projectforge/app"
	"projectforge.dev/projectforge/app/controller/cutil"
	"projectforge.dev/projectforge/app/lib/exec"
	"projectforge.dev/projectforge/app/project"
	"projectforge.dev/projectforge/views/layout"
)

//line views/vproject/List.html:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vproject/List.html:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vproject/List.html:10
type List struct {
	layout.Basic
	Projects project.Projects
	Execs    exec.Execs
	Icon     string
	Tags     []string
}

//line views/vproject/List.html:18
func (p *List) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vproject/List.html:18
	qw422016.N().S(`
  <div class="card">
    `)
//line views/vproject/List.html:20
	StreamAvailActions(qw422016, "", p.Tags, p.Projects.Tags(), p.Icon, ps)
//line views/vproject/List.html:20
	qw422016.N().S(`
  </div>
  `)
//line views/vproject/List.html:22
	StreamTable(qw422016, p.Projects, p.Tags, true, p.Execs, as, ps)
//line views/vproject/List.html:22
	qw422016.N().S(`
`)
//line views/vproject/List.html:23
}

//line views/vproject/List.html:23
func (p *List) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vproject/List.html:23
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vproject/List.html:23
	p.StreamBody(qw422016, as, ps)
//line views/vproject/List.html:23
	qt422016.ReleaseWriter(qw422016)
//line views/vproject/List.html:23
}

//line views/vproject/List.html:23
func (p *List) Body(as *app.State, ps *cutil.PageState) string {
//line views/vproject/List.html:23
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vproject/List.html:23
	p.WriteBody(qb422016, as, ps)
//line views/vproject/List.html:23
	qs422016 := string(qb422016.B)
//line views/vproject/List.html:23
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vproject/List.html:23
	return qs422016
//line views/vproject/List.html:23
}
