// Code generated by qtc from "Summary.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vproject/Summary.html:1
package vproject

//line views/vproject/Summary.html:1
import (
	"github.com/kyleu/projectforge/app/action"
	"github.com/kyleu/projectforge/app/controller/cutil"
	"github.com/kyleu/projectforge/app/project"
	"github.com/kyleu/projectforge/views/components"
	"strings"
)

//line views/vproject/Summary.html:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vproject/Summary.html:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vproject/Summary.html:9
func StreamSummary(qw422016 *qt422016.Writer, prj *project.Project, ps *cutil.PageState, path ...string) {
//line views/vproject/Summary.html:9
	qw422016.N().S(`
  <div class="card">
    <div class="right"><a href="#modal-project-`)
//line views/vproject/Summary.html:11
	qw422016.E().S(prj.Key)
//line views/vproject/Summary.html:11
	qw422016.N().S(`"><button type="button">JSON</button></a></div>
    <h3>`)
//line views/vproject/Summary.html:12
	components.StreamSVGRefIcon(qw422016, prj.SafeIcon(), ps)
//line views/vproject/Summary.html:12
	qw422016.N().S(` `)
//line views/vproject/Summary.html:12
	qw422016.E().S(prj.Title())
//line views/vproject/Summary.html:12
	qw422016.N().S(`</h3>
    <div style="display: flex;">
      <div style="flex-grow: 1;">
        <h4>Generate</h4>
`)
//line views/vproject/Summary.html:16
	for _, t := range action.ProjectTypes {
//line views/vproject/Summary.html:16
		qw422016.N().S(`        <a href="/run/`)
//line views/vproject/Summary.html:17
		qw422016.E().S(prj.Key)
//line views/vproject/Summary.html:17
		qw422016.N().S(`/`)
//line views/vproject/Summary.html:17
		qw422016.E().S(t.Key)
//line views/vproject/Summary.html:17
		qw422016.N().S(`" title="`)
//line views/vproject/Summary.html:17
		qw422016.E().S(t.Description)
//line views/vproject/Summary.html:17
		qw422016.N().S(`"><button>`)
//line views/vproject/Summary.html:17
		qw422016.E().S(t.Title)
//line views/vproject/Summary.html:17
		qw422016.N().S(`</button></a>
`)
//line views/vproject/Summary.html:18
	}
//line views/vproject/Summary.html:18
	qw422016.N().S(`      </div>
      <div style="flex-grow: 1;">
`)
//line views/vproject/Summary.html:21
	if len(path) == 0 {
//line views/vproject/Summary.html:21
		qw422016.N().S(`        <h4>Maintain</h4>
        <a href="/p/`)
//line views/vproject/Summary.html:23
		qw422016.E().S(prj.Key)
//line views/vproject/Summary.html:23
		qw422016.N().S(`/fs" title="Explore the project's files"><button>Filesystem</button></a>
        <a href="/p/`)
//line views/vproject/Summary.html:24
		qw422016.E().S(prj.Key)
//line views/vproject/Summary.html:24
		qw422016.N().S(`/svg" title="Add new SVGs and set the app icon"><button>Manage SVGs</button></a>
`)
//line views/vproject/Summary.html:25
	} else {
//line views/vproject/Summary.html:25
		qw422016.N().S(`        <h4>Files</h4>
`)
//line views/vproject/Summary.html:27
		var ctx []string

//line views/vproject/Summary.html:28
		for _, pth := range path {
//line views/vproject/Summary.html:29
			ctx = append(ctx, pth)

//line views/vproject/Summary.html:29
			qw422016.N().S(`        <a href="/p/`)
//line views/vproject/Summary.html:30
			qw422016.E().S(prj.Key)
//line views/vproject/Summary.html:30
			qw422016.N().S(`/fs/`)
//line views/vproject/Summary.html:30
			qw422016.E().S(strings.Join(ctx, `/`))
//line views/vproject/Summary.html:30
			qw422016.N().S(`"><button>`)
//line views/vproject/Summary.html:30
			qw422016.E().S(pth)
//line views/vproject/Summary.html:30
			qw422016.N().S(`}</button></a>
`)
//line views/vproject/Summary.html:31
		}
//line views/vproject/Summary.html:32
	}
//line views/vproject/Summary.html:32
	qw422016.N().S(`      </div>
      <div style="flex-grow: 1;">
        <h4>Build</h4>
`)
//line views/vproject/Summary.html:36
	for _, b := range action.AllBuilds {
//line views/vproject/Summary.html:36
		qw422016.N().S(`        <a href="/run/`)
//line views/vproject/Summary.html:37
		qw422016.E().S(prj.Key)
//line views/vproject/Summary.html:37
		qw422016.N().S(`/build?phase=`)
//line views/vproject/Summary.html:37
		qw422016.E().S(b.Key)
//line views/vproject/Summary.html:37
		qw422016.N().S(`" title="`)
//line views/vproject/Summary.html:37
		qw422016.E().S(b.Description)
//line views/vproject/Summary.html:37
		qw422016.N().S(`"><button>`)
//line views/vproject/Summary.html:37
		qw422016.E().S(b.Title)
//line views/vproject/Summary.html:37
		qw422016.N().S(`</button></a>
`)
//line views/vproject/Summary.html:38
	}
//line views/vproject/Summary.html:38
	qw422016.N().S(`      </div>
    </div>
  </div>
  `)
//line views/vproject/Summary.html:42
	components.StreamJSONModal(qw422016, "project-"+prj.Key, "Project JSON", prj, 1)
//line views/vproject/Summary.html:42
	qw422016.N().S(`
`)
//line views/vproject/Summary.html:43
}

//line views/vproject/Summary.html:43
func WriteSummary(qq422016 qtio422016.Writer, prj *project.Project, ps *cutil.PageState, path ...string) {
//line views/vproject/Summary.html:43
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vproject/Summary.html:43
	StreamSummary(qw422016, prj, ps, path...)
//line views/vproject/Summary.html:43
	qt422016.ReleaseWriter(qw422016)
//line views/vproject/Summary.html:43
}

//line views/vproject/Summary.html:43
func Summary(prj *project.Project, ps *cutil.PageState, path ...string) string {
//line views/vproject/Summary.html:43
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vproject/Summary.html:43
	WriteSummary(qb422016, prj, ps, path...)
//line views/vproject/Summary.html:43
	qs422016 := string(qb422016.B)
//line views/vproject/Summary.html:43
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vproject/Summary.html:43
	return qs422016
//line views/vproject/Summary.html:43
}
