// Code generated by qtc from "Render.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Code generated by Project Forge, see https://projectforge.dev for details. -->

//line views/Render.html:2
package views

//line views/Render.html:2
import (
	"fmt"
	"github.com/kyleu/projectforge/app"
	"github.com/kyleu/projectforge/app/controller/cutil"
	"github.com/kyleu/projectforge/app/util"
	"github.com/kyleu/projectforge/views/components"
	"github.com/kyleu/projectforge/views/layout"
	"sort"
)

//line views/Render.html:12
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/Render.html:12
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/Render.html:12
func StreamRender(qw422016 *qt422016.Writer, page layout.Page, as *app.State, ps *cutil.PageState) {
//line views/Render.html:13
	defer func() {
		x := recover()
		if x != nil {
			ps.Logger.Error(fmt.Sprintf("Error processing template [%T]: %+v", x, x))
			panic(x)
		}
	}()

//line views/Render.html:20
	qw422016.N().S(`<!DOCTYPE html>
<html lang="en">
<!-- `)
//line views/Render.html:22
	qw422016.E().S(cutil.PageComment)
//line views/Render.html:22
	qw422016.N().S(` -->
<head>`)
//line views/Render.html:23
	page.StreamHead(qw422016, as, ps)
//line views/Render.html:23
	qw422016.N().S(`</head>
`)
//line views/Render.html:24
	if ps.Profile.Mode != "" {
//line views/Render.html:24
		qw422016.N().S(`<body class="`)
//line views/Render.html:24
		qw422016.E().S(ps.Profile.ModeClass())
//line views/Render.html:24
		qw422016.N().S(`">`)
//line views/Render.html:24
	} else {
//line views/Render.html:24
		qw422016.N().S(`<body>`)
//line views/Render.html:24
	}
//line views/Render.html:25
	if len(ps.Flashes) > 0 {
//line views/Render.html:25
		streamrenderFlashes(qw422016, ps.Flashes)
//line views/Render.html:25
	}
//line views/Render.html:26
	page.StreamNav(qw422016, as, ps)
//line views/Render.html:26
	qw422016.N().S(`
<main id="content">`)
//line views/Render.html:27
	page.StreamBody(qw422016, as, ps)
//line views/Render.html:27
	qw422016.N().S(`</main>
`)
//line views/Render.html:28
	sort.Strings(ps.Icons)

//line views/Render.html:29
	if len(ps.Icons) > 0 {
//line views/Render.html:29
		qw422016.N().S(`<div class="icon-list" style="display: none;">`)
//line views/Render.html:29
		for _, icon := range ps.Icons {
//line views/Render.html:29
			qw422016.N().S(`
  `)
//line views/Render.html:30
			components.StreamSVG(qw422016, icon)
//line views/Render.html:30
		}
//line views/Render.html:30
		qw422016.N().S(`
</div>
`)
//line views/Render.html:32
	}
//line views/Render.html:32
	qw422016.N().S(`</body>
</html>
`)
//line views/Render.html:34
}

//line views/Render.html:34
func WriteRender(qq422016 qtio422016.Writer, page layout.Page, as *app.State, ps *cutil.PageState) {
//line views/Render.html:34
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/Render.html:34
	StreamRender(qw422016, page, as, ps)
//line views/Render.html:34
	qt422016.ReleaseWriter(qw422016)
//line views/Render.html:34
}

//line views/Render.html:34
func Render(page layout.Page, as *app.State, ps *cutil.PageState) string {
//line views/Render.html:34
	qb422016 := qt422016.AcquireByteBuffer()
//line views/Render.html:34
	WriteRender(qb422016, page, as, ps)
//line views/Render.html:34
	qs422016 := string(qb422016.B)
//line views/Render.html:34
	qt422016.ReleaseByteBuffer(qb422016)
//line views/Render.html:34
	return qs422016
//line views/Render.html:34
}

//line views/Render.html:36
func streamrenderFlashes(qw422016 *qt422016.Writer, flashes []string) {
//line views/Render.html:37
	if len(flashes) > 0 {
//line views/Render.html:37
		qw422016.N().S(`<div id="flash-container">`)
//line views/Render.html:39
		for idx, f := range flashes {
//line views/Render.html:40
			level, msg := util.SplitString(f, ':', true)

//line views/Render.html:40
			qw422016.N().S(`<div class="flash"><input type="radio" style="display:none;" id="hide-flash-`)
//line views/Render.html:42
			qw422016.N().D(idx)
//line views/Render.html:42
			qw422016.N().S(`"><label for="hide-flash-`)
//line views/Render.html:43
			qw422016.N().D(idx)
//line views/Render.html:43
			qw422016.N().S(`"><span>×</span></label><div class="content flash-`)
//line views/Render.html:44
			qw422016.E().S(level)
//line views/Render.html:44
			qw422016.N().S(`">`)
//line views/Render.html:45
			qw422016.E().S(msg)
//line views/Render.html:45
			qw422016.N().S(`</div></div>`)
//line views/Render.html:48
		}
//line views/Render.html:48
		qw422016.N().S(`</div>`)
//line views/Render.html:50
	}
//line views/Render.html:51
}

//line views/Render.html:51
func writerenderFlashes(qq422016 qtio422016.Writer, flashes []string) {
//line views/Render.html:51
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/Render.html:51
	streamrenderFlashes(qw422016, flashes)
//line views/Render.html:51
	qt422016.ReleaseWriter(qw422016)
//line views/Render.html:51
}

//line views/Render.html:51
func renderFlashes(flashes []string) string {
//line views/Render.html:51
	qb422016 := qt422016.AcquireByteBuffer()
//line views/Render.html:51
	writerenderFlashes(qb422016, flashes)
//line views/Render.html:51
	qs422016 := string(qb422016.B)
//line views/Render.html:51
	qt422016.ReleaseByteBuffer(qb422016)
//line views/Render.html:51
	return qs422016
//line views/Render.html:51
}
