// Code generated by qtc from "List.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Code generated by Project Forge, see https://projectforge.dev for details. -->

//line views/vtools/List.html:2
package vtools

//line views/vtools/List.html:2
import (
	"github.com/kyleu/projectforge/app"
	"github.com/kyleu/projectforge/app/controller/cutil"
	"github.com/kyleu/projectforge/views/layout"
)

//line views/vtools/List.html:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vtools/List.html:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vtools/List.html:8
type List struct{ layout.Basic }

//line views/vtools/List.html:10
func (p *List) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vtools/List.html:10
	qw422016.N().S(`
  <div class="card">
    <h3>Available Tools</h3>
    <ul>
      <li><a href="/tools/svg">SVG Editor (temp)</a></li>
    </ul>
  </div>
`)
//line views/vtools/List.html:17
}

//line views/vtools/List.html:17
func (p *List) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vtools/List.html:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vtools/List.html:17
	p.StreamBody(qw422016, as, ps)
//line views/vtools/List.html:17
	qt422016.ReleaseWriter(qw422016)
//line views/vtools/List.html:17
}

//line views/vtools/List.html:17
func (p *List) Body(as *app.State, ps *cutil.PageState) string {
//line views/vtools/List.html:17
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vtools/List.html:17
	p.WriteBody(qb422016, as, ps)
//line views/vtools/List.html:17
	qs422016 := string(qb422016.B)
//line views/vtools/List.html:17
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vtools/List.html:17
	return qs422016
//line views/vtools/List.html:17
}
