# Content managed by Project Forge, see [projectforge.md] for details.
# http://goreleaser.com
project_name: projectforge

archives:
  - format: zip
    wrap_in_directory: "false"
    replacements: &replacements
      darwin: "macos"
      386: "i386"
      amd64: "x86_64"
    files:
      - none*

brews:
  -
    tap:
      owner: "kyleu"
      name: "homebrew-kyleu"
    commit_author:
      name: "Kyle U"
      email: "kyle@kyleu.com"
    folder: Formula
    homepage: "https://projectforge.dev"
    description: "Project Forge helps you build and maintain feature-rich applications written in the Go programming language."
    license: "Proprietary"
    skip_upload: "false"
    url_template: "https://update.projectforge.dev/release/{{ .Tag }}/{{ .ArtifactName }}"
    install: "bin.install \"program\""

changelog:
  skip: true

checksum:
  name_template: "checksums.txt"
  extra_files:
    - glob: "./build/dist/*_notarized.zip"
    - glob: "./build/dist/*_desktop.dmg"
    - glob: "./build/dist/*_desktop.zip"
    - glob: "./build/dist/*_aar.zip"
    - glob: "./build/dist/*_apk.zip"
    - glob: "./build/dist/*_framework.zip"
    - glob: "./build/dist/*_app.zip"
    # $PF_SECTION_START(checksums)$
    - glob: "./build/dist/projectforge_module_*.zip"
    # $PF_SECTION_END(checksums)$

dockers:
  -
    image_templates:
      - "ghcr.io/kyleu/projectforge:{{ .Major }}"
      - "ghcr.io/kyleu/projectforge:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/kyleu/projectforge:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "ghcr.io/kyleu/projectforge:latest"
    dockerfile: ./tools/release/Dockerfile
  -
    image_templates:
      - "ghcr.io/kyleu/projectforge:{{ .Major }}-debug"
      - "ghcr.io/kyleu/projectforge:{{ .Major }}.{{ .Minor }}-debug"
      - "ghcr.io/kyleu/projectforge:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-debug"
      - "ghcr.io/kyleu/projectforge:latest-debug"
    dockerfile: ./tools/release/debug.Dockerfile

dist: "build/dist"

nfpms:
  -
    vendor: "Kyle U"
    homepage: "https://projectforge.dev}"
    maintainer: "Kyle U <kyle@kyleu.com>"
    description: "Project Forge helps you build and maintain feature-rich applications written in the Go programming language."
    license: "Proprietary"
    replacements: *replacements
    formats:
      - apk
      - deb
      - rpm

release:
  draft: false
  header: |
    ## {{ .Version }} ({{ .Date }})
    See https://projectforge.dev for download links and documentation
    ## Main downloads
    - [Linux Intel 64 bit](https://github.com/kyleu/projectforge/releases/download/{{ .Tag }}/projectforge_{{ .Version }}_linux_x86_64.zip)
    - [MacOS Universal](https://github.com/kyleu/projectforge/releases/download/{{ .Tag }}/projectforge_{{ .Version }}_macos_all.zip)
    - [Windows Intel 64 bit](https://github.com/kyleu/projectforge/releases/download/{{ .Tag }}/projectforge_{{ .Version }}_windows_x86_64.zip)

  extra_files:
    - glob: "./build/dist/*_notarized.zip"
    - glob: "./build/dist/*.dmg"
    - glob: "./build/dist/*_desktop.zip"
    - glob: "./build/dist/*_aar.zip"
    - glob: "./build/dist/*_apk.zip"
    - glob: "./build/dist/*_framework.zip"
    - glob: "./build/dist/*_app.zip"
    # $PF_SECTION_START(releasefiles)$
    - glob: "./build/dist/projectforge_module_*.zip"
    # $PF_SECTION_END(releasefiles)$

signs:
  - artifacts: checksum

snapcrafts:
  -
    publish: false
    replacements: *replacements
    summary: "Build and maintain feature-rich applications using Golang"
    description: "Project Forge helps you build and maintain feature-rich applications written in the Go programming language."
    grade: stable
    confinement: strict
    license: "Proprietary"

snapshot:
  name_template: "{{ .Tag }}"

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"
  format: "zip"

universal_binaries:
- id: "darwin"
  replace: false
  name_template: '{{ .ProjectName }}'

builds:
  - id: "darwin"
    goos:
      - darwin
    goarch:
      - "amd64"
      - "arm64"
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "linux"
    goos:
      - "linux"
    goarch:
      - "386"
      - "amd64"
      - "arm64"
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "linux-arm"
    goos:
      - "linux"
    goarch:
      - "arm"
    goarm:
      - "5"
      - "6"
      - "7"
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "linux-mips"
    goos:
      - "linux"
    goarch:
      - "mips"
      - "mipsle"
      - "mips64"
      - "mips64le"
    gomips:
      - "hardfloat"
      - "softfloat"
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "linux-odd"
    goos:
      - "linux"
    goarch:
      - "ppc64"
      - "ppc64le"
      - "riscv64"
      - "s390x"
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "windows"
    goos:
      - "windows"
    goarch:
      - "amd64"
    mod_timestamp: "{{ .CommitTimestamp }}"
    hooks:
      # This build uses only one architecture, and is a good place to put one-time use scripts
      post:
        - "./bin/build/desktop.release.sh {{ .Version }}"
        - "./bin/build/android.sh {{ .Version }}"
        - "./bin/build/ios.sh {{ .Version }}"
        - "./tools/notarize/notarize.sh"
        # $PF_SECTION_START(extrascripts)$
        - "./bin/build/modules.sh"
        # $PF_SECTION_END(extrascripts)$

  - id: "windows_i386"
    goos:
      - "windows"
    goarch:
      - "386"
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "windows-arm"
    goos:
      - "windows"
    goarch:
      - "arm"
      - "arm64"
    goarm:
      - "5"
      - "6"
      - "7"
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "js"
    goos:
      - "js"
    goarch:
      - "wasm"
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "dragonfly"
    goos:
      - "dragonfly"
    goarch:
      - "amd64"
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "illumos"
    goos:
      - "illumos"
    goarch:
      - "amd64"
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "freebsd"
    goos:
      - "freebsd"
    goarch:
      - "386"
      - "amd64"
      - "arm"
      - "arm64"
    goarm:
      - "5"
      - "6"
      - "7"
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "netbsd"
    goos:
      - "netbsd"
    goarch:
      - "386"
      - "amd64"
      - "arm"
      - "arm64"
    goarm:
      - "7"
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "openbsd"
    goos:
      - "openbsd"
    goarch:
      - "386"
      - "amd64"
      - "arm"
      - "arm64"
    goarm:
      - "5"
      - "6"
      - "7"
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "plan9"
    goos:
      - "plan9"
    goarch:
      - "386"
      - "amd64"
      - "arm"
    goarm:
      - "5"
      - "6"
      - "7"
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "solaris"
    goos:
      - "solaris"
    goarch:
      - "amd64"
    mod_timestamp: "{{ .CommitTimestamp }}"
