// Code generated by qtc from "String.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/components/fieldview/String.html:2
package fieldview

//line views/components/fieldview/String.html:2
import (
	"strings"
)

//line views/components/fieldview/String.html:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/components/fieldview/String.html:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/components/fieldview/String.html:6
func StreamString(qw422016 *qt422016.Writer, v string) {
//line views/components/fieldview/String.html:7
	if len(v) == 0 {
//line views/components/fieldview/String.html:7
		qw422016.N().S(`<em>empty string</em>`)
//line views/components/fieldview/String.html:9
	} else if strings.Contains(v, "\n") {
//line views/components/fieldview/String.html:9
		qw422016.N().S(`<div class="pre">`)
//line views/components/fieldview/String.html:10
		qw422016.E().S(strings.TrimSpace(v))
//line views/components/fieldview/String.html:10
		qw422016.N().S(`</div>`)
//line views/components/fieldview/String.html:11
	} else {
//line views/components/fieldview/String.html:12
		qw422016.E().S(v)
//line views/components/fieldview/String.html:13
	}
//line views/components/fieldview/String.html:14
}

//line views/components/fieldview/String.html:14
func WriteString(qq422016 qtio422016.Writer, v string) {
//line views/components/fieldview/String.html:14
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/fieldview/String.html:14
	StreamString(qw422016, v)
//line views/components/fieldview/String.html:14
	qt422016.ReleaseWriter(qw422016)
//line views/components/fieldview/String.html:14
}

//line views/components/fieldview/String.html:14
func String(v string) string {
//line views/components/fieldview/String.html:14
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/fieldview/String.html:14
	WriteString(qb422016, v)
//line views/components/fieldview/String.html:14
	qs422016 := string(qb422016.B)
//line views/components/fieldview/String.html:14
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/fieldview/String.html:14
	return qs422016
//line views/components/fieldview/String.html:14
}
