// Code generated by qtc from "List.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vtest/List.html:1
package vtest

//line views/vtest/List.html:1
import (
	"projectforge.dev/projectforge/app"
	"projectforge.dev/projectforge/app/controller/cutil"
	"projectforge.dev/projectforge/views/components"
	"projectforge.dev/projectforge/views/layout"
)

//line views/vtest/List.html:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vtest/List.html:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vtest/List.html:8
type List struct{ layout.Basic }

//line views/vtest/List.html:10
func (p *List) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vtest/List.html:10
	qw422016.N().S(`
  <div class="card">
    <h3>`)
//line views/vtest/List.html:12
	components.StreamSVGIcon(qw422016, `list`, ps)
//line views/vtest/List.html:12
	qw422016.N().S(` Tests</h3>
    <div class="mt">
      <a href="/test/bootstrap"><button>Rebuild test project</button></a>
      <a href="/test/diff"><button>Text diff tests</button></a>
    </div>
  </div>
  <div class="card">
    <h3>`)
//line views/vtest/List.html:19
	components.StreamSVGIcon(qw422016, `search`, ps)
//line views/vtest/List.html:19
	qw422016.N().S(` Search Project Definitions</h3>
    <form action="/test/search" method="get" class="mt">
      <input type="text" name="q" placeholder="Search..." />
      <button type="submit">Search</button>
    </form>
  </div>
  <div class="card">
    <h3>`)
//line views/vtest/List.html:26
	components.StreamSVGIcon(qw422016, `paperclip`, ps)
//line views/vtest/List.html:26
	qw422016.N().S(` JSON Schema</h3>
    <div class="mt">
      <a href="/test/jsonschema-init"><button type="button">Initialize</button></a>
      <a href="/test/jsonschema-test"><button type="button">Test</button></a>
    </div>
  </div>
  <div class="card">
    <h3>`)
//line views/vtest/List.html:33
	components.StreamSVGIcon(qw422016, `archive`, ps)
//line views/vtest/List.html:33
	qw422016.N().S(` Libraries</h3>
    <div class="mt">
      <a href="/test/libraries"><button type="button">Manage external libraries</button></a>
      <a href="/test/readmes"><button type="button">Generate module readmes</button></a>
    </div>
  </div>
`)
//line views/vtest/List.html:39
}

//line views/vtest/List.html:39
func (p *List) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vtest/List.html:39
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vtest/List.html:39
	p.StreamBody(qw422016, as, ps)
//line views/vtest/List.html:39
	qt422016.ReleaseWriter(qw422016)
//line views/vtest/List.html:39
}

//line views/vtest/List.html:39
func (p *List) Body(as *app.State, ps *cutil.PageState) string {
//line views/vtest/List.html:39
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vtest/List.html:39
	p.WriteBody(qb422016, as, ps)
//line views/vtest/List.html:39
	qs422016 := string(qb422016.B)
//line views/vtest/List.html:39
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vtest/List.html:39
	return qs422016
//line views/vtest/List.html:39
}
