// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vmodule/Detail.html:1
package vmodule

//line views/vmodule/Detail.html:1
import (
	"github.com/kyleu/projectforge/app"
	"github.com/kyleu/projectforge/app/controller/cutil"
	"github.com/kyleu/projectforge/app/module"
	"github.com/kyleu/projectforge/views/layout"
)

//line views/vmodule/Detail.html:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vmodule/Detail.html:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vmodule/Detail.html:8
type Detail struct {
	layout.Basic
	Module *module.Module
}

//line views/vmodule/Detail.html:13
func (p *Detail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vmodule/Detail.html:13
	qw422016.N().S(`
`)
//line views/vmodule/Detail.html:14
	mod := p.Module

//line views/vmodule/Detail.html:14
	qw422016.N().S(`  `)
//line views/vmodule/Detail.html:15
	StreamSummary(qw422016, mod)
//line views/vmodule/Detail.html:15
	qw422016.N().S(`
  <div class="card">
    <h3>Details</h3>
    <table class="mt">
      <tbody>
        <tr>
          <th>Key</th>
          <td>`)
//line views/vmodule/Detail.html:22
	qw422016.E().S(mod.Key)
//line views/vmodule/Detail.html:22
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th>Name</th>
          <td>`)
//line views/vmodule/Detail.html:26
	qw422016.E().S(mod.Name)
//line views/vmodule/Detail.html:26
	qw422016.N().S(`</td>
        </tr>
      </tbody>
    </table>
  </div>
`)
//line views/vmodule/Detail.html:31
}

//line views/vmodule/Detail.html:31
func (p *Detail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vmodule/Detail.html:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vmodule/Detail.html:31
	p.StreamBody(qw422016, as, ps)
//line views/vmodule/Detail.html:31
	qt422016.ReleaseWriter(qw422016)
//line views/vmodule/Detail.html:31
}

//line views/vmodule/Detail.html:31
func (p *Detail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vmodule/Detail.html:31
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vmodule/Detail.html:31
	p.WriteBody(qb422016, as, ps)
//line views/vmodule/Detail.html:31
	qs422016 := string(qb422016.B)
//line views/vmodule/Detail.html:31
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vmodule/Detail.html:31
	return qs422016
//line views/vmodule/Detail.html:31
}
