// Code generated by qtc from "Download.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Code generated by Project Forge, see https://projectforge.dev for details. -->

//line views/vsite/Download.html:2
package vsite

//line views/vsite/Download.html:2
import (
	"github.com/kyleu/projectforge/app"
	"github.com/kyleu/projectforge/app/controller/cutil"
	"github.com/kyleu/projectforge/app/site/download"
	"github.com/kyleu/projectforge/app/util"
	"github.com/kyleu/projectforge/views/layout"
)

//line views/vsite/Download.html:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vsite/Download.html:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vsite/Download.html:10
type Download struct {
	layout.Basic
	Links download.Links
}

//line views/vsite/Download.html:15
func (p *Download) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vsite/Download.html:15
	qw422016.N().S(`
  <div class="card">
    <h3>Download `)
//line views/vsite/Download.html:17
	qw422016.E().S(util.AppName)
//line views/vsite/Download.html:17
	qw422016.N().S(` `)
//line views/vsite/Download.html:17
	qw422016.E().S(as.BuildInfo.Version)
//line views/vsite/Download.html:17
	qw422016.N().S(`</h3>
  </div>

  <div class="card">
    <h3>Desktop Version</h3>
    <em>Standalone application using your platform's native web viewer</em>
    <ul>
`)
//line views/vsite/Download.html:24
	for _, link := range p.Links.GetByModes("desktop") {
//line views/vsite/Download.html:24
		qw422016.N().S(`      <li><a href="https://github.com/kyleu/projectforge/releases/download/v`)
//line views/vsite/Download.html:25
		qw422016.E().S(as.BuildInfo.Version)
//line views/vsite/Download.html:25
		qw422016.N().S(`/`)
//line views/vsite/Download.html:25
		qw422016.E().S(link.URL)
//line views/vsite/Download.html:25
		qw422016.N().S(`">`)
//line views/vsite/Download.html:25
		qw422016.E().S(link.OSString())
//line views/vsite/Download.html:25
		qw422016.N().S(`</a></li>
`)
//line views/vsite/Download.html:26
	}
//line views/vsite/Download.html:26
	qw422016.N().S(`    </ul>
  </div>

  <div class="card">
    <h3>Server Version</h3>
    <em>A command line interface that can launch a web server</em>
    <table class="mt">
      <tbody>
`)
//line views/vsite/Download.html:35
	var currentOS string

//line views/vsite/Download.html:36
	for _, link := range p.Links.GetByModes("server", "mobile") {
//line views/vsite/Download.html:37
		if currentOS != link.OS {
//line views/vsite/Download.html:38
			if currentOS != "" {
//line views/vsite/Download.html:38
				qw422016.N().S(`          </td>
        </tr>
`)
//line views/vsite/Download.html:41
			}
//line views/vsite/Download.html:42
			currentOS = link.OS

//line views/vsite/Download.html:42
			qw422016.N().S(`        <tr>
          <td>`)
//line views/vsite/Download.html:44
			qw422016.E().S(link.OSString())
//line views/vsite/Download.html:44
			qw422016.N().S(`</td>
          <td>
`)
//line views/vsite/Download.html:46
		}
//line views/vsite/Download.html:47
		if link.OS == "linux" && (link.Arch == "ppc64" || link.Arch == "mips64_hardfloat" || link.Arch == "mips_hardfloat") {
//line views/vsite/Download.html:47
			qw422016.N().S(`            <br />
`)
//line views/vsite/Download.html:49
		}
//line views/vsite/Download.html:49
		qw422016.N().S(`            <a href="https://github.com/kyleu/projectforge/releases/download/v`)
//line views/vsite/Download.html:50
		qw422016.E().S(as.BuildInfo.Version)
//line views/vsite/Download.html:50
		qw422016.N().S(`/`)
//line views/vsite/Download.html:50
		qw422016.E().S(link.URL)
//line views/vsite/Download.html:50
		qw422016.N().S(`">`)
//line views/vsite/Download.html:50
		qw422016.E().S(link.Arch)
//line views/vsite/Download.html:50
		qw422016.N().S(`</a>
`)
//line views/vsite/Download.html:51
	}
//line views/vsite/Download.html:51
	qw422016.N().S(`          </td>
        </tr>
      </tbody>
    </table>
  </div>
`)
//line views/vsite/Download.html:57
}

//line views/vsite/Download.html:57
func (p *Download) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vsite/Download.html:57
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vsite/Download.html:57
	p.StreamBody(qw422016, as, ps)
//line views/vsite/Download.html:57
	qt422016.ReleaseWriter(qw422016)
//line views/vsite/Download.html:57
}

//line views/vsite/Download.html:57
func (p *Download) Body(as *app.State, ps *cutil.PageState) string {
//line views/vsite/Download.html:57
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vsite/Download.html:57
	p.WriteBody(qb422016, as, ps)
//line views/vsite/Download.html:57
	qs422016 := string(qb422016.B)
//line views/vsite/Download.html:57
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vsite/Download.html:57
	return qs422016
//line views/vsite/Download.html:57
}
