// Code generated by qtc from "Help.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Code generated by Project Forge, see https://projectforge.dev for details. -->

//line views/vhelp/Help.html:2
package vhelp

//line views/vhelp/Help.html:2
import (
	"github.com/kyleu/projectforge/app"
	"github.com/kyleu/projectforge/app/controller/cutil"
	"github.com/kyleu/projectforge/app/util"
	"github.com/kyleu/projectforge/views/layout"
	"github.com/kyleu/projectforge/views/vsettings"
)

//line views/vhelp/Help.html:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vhelp/Help.html:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vhelp/Help.html:10
type Help struct{ layout.Basic }

//line views/vhelp/Help.html:12
func (p *Help) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vhelp/Help.html:12
	qw422016.N().S(`
  `)
//line views/vhelp/Help.html:13
	vsettings.StreamAbout(qw422016, as)
//line views/vhelp/Help.html:13
	qw422016.N().S(`
  <div class="card">
    <h3>Help</h3>
    <p>Coming soon...</p>
  </div>
  `)
//line views/vhelp/Help.html:18
	StreamFeedback(qw422016)
//line views/vhelp/Help.html:18
	qw422016.N().S(`
`)
//line views/vhelp/Help.html:19
}

//line views/vhelp/Help.html:19
func (p *Help) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vhelp/Help.html:19
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vhelp/Help.html:19
	p.StreamBody(qw422016, as, ps)
//line views/vhelp/Help.html:19
	qt422016.ReleaseWriter(qw422016)
//line views/vhelp/Help.html:19
}

//line views/vhelp/Help.html:19
func (p *Help) Body(as *app.State, ps *cutil.PageState) string {
//line views/vhelp/Help.html:19
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vhelp/Help.html:19
	p.WriteBody(qb422016, as, ps)
//line views/vhelp/Help.html:19
	qs422016 := string(qb422016.B)
//line views/vhelp/Help.html:19
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vhelp/Help.html:19
	return qs422016
//line views/vhelp/Help.html:19
}

//line views/vhelp/Help.html:21
func StreamFeedback(qw422016 *qt422016.Writer) {
//line views/vhelp/Help.html:21
	qw422016.N().S(`
  <div class="card">
    <h3>Feedback</h3>
    <p>For now, email <a href="mailto:`)
//line views/vhelp/Help.html:24
	qw422016.E().S(util.AppContact)
//line views/vhelp/Help.html:24
	qw422016.N().S(`">`)
//line views/vhelp/Help.html:24
	qw422016.E().S(util.AppContact)
//line views/vhelp/Help.html:24
	qw422016.N().S(`</a></p>
  </div>
`)
//line views/vhelp/Help.html:26
}

//line views/vhelp/Help.html:26
func WriteFeedback(qq422016 qtio422016.Writer) {
//line views/vhelp/Help.html:26
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vhelp/Help.html:26
	StreamFeedback(qw422016)
//line views/vhelp/Help.html:26
	qt422016.ReleaseWriter(qw422016)
//line views/vhelp/Help.html:26
}

//line views/vhelp/Help.html:26
func Feedback() string {
//line views/vhelp/Help.html:26
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vhelp/Help.html:26
	WriteFeedback(qb422016)
//line views/vhelp/Help.html:26
	qs422016 := string(qb422016.B)
//line views/vhelp/Help.html:26
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vhelp/Help.html:26
	return qs422016
//line views/vhelp/Help.html:26
}
