# http://goreleaser.com
env:
  - XNAME={{{ .AuthorName }}}
  - XEMAIL={{{ .AuthorEmail }}}
  - XORG={{{ .Org }}}
  - XHOMEPAGE={{{ .Homepage }}}
  - XLICENSE={{{ .License }}}
  - XSUMMARY={{{ .Summary }}}
  - XDESCRIPTION={{{ .Description }}}
  - XSKIP_DESKTOP={{{ .SkipDesktop }}}
  - XSKIP_ANDROID={{{ .SkipAndroid }}}
  - XSKIP_IOS={{{ .SkipIOS }}}
  - XSKIP_NOTARIZE={{{ .SkipNotarize }}}
brews:
  -
    tap:
      owner: "{{{ .Org }}}"
      name: "homebrew-{{{ .Org }}}"
    commit_author:
      name: "{{{ .AuthorName }}}"
      email: "{{{ .AuthorEmail }}}"
    folder: Formula
    homepage: "{{ .Env.XHOMEPAGE }}"
    description: "{{ .Env.XDESCRIPTION }}"
    license: "{{ .Env.XLICENSE }}"
    skip_upload: {{{ .SkipHomebrew }}}

signs:
  - artifacts: checksum

archives:
  - format: zip
    wrap_in_directory: false
    replacements: &replacements
      darwin: macos
      386: i386
      amd64: x86_64
    files:
      - none*

# Everything below this line is generic

dist: "build/dist"

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"
  format: "zip"

snapshot:
  name_template: "{{ .Tag }}"

release:
  draft: true
  header: |
    ## {{ .Version }} ({{ .Date }})
    See {{{ .Homepage }}} for download links and documentation
    ## Main downloads
    - [Linux Intel 64 bit]({{{ .Sourcecode }}}/releases/download/{{ .Version }}/{{ .ProjectName }}_{{ .Version }}_linux_x86_64.zip)
    - [MacOS Intel 64 bit]({{{ .Sourcecode }}}/releases/download/{{ .Version }}/{{ .ProjectName }}_{{ .Version }}_macos_x86_64.zip)
    - [Windows Intel 64 bit]({{{ .Sourcecode }}}/releases/download/{{ .Version }}/{{ .ProjectName }}_{{ .Version }}_windows_x86_64.zip)

  extra_files:
    - glob: "./build/dist/*_notarized.zip"
    - glob: "./build/dist/*.dmg"
    - glob: "./build/dist/*_desktop_*.zip"
    - glob: "./build/dist/*_mobile_*.zip"

changelog:
  skip: true

checksum:
  name_template: "checksums.txt"

dockers:
  -
    image_templates:
      - "ghcr.io/{{ .Env.XORG }}/{{.ProjectName}}:{{ .Tag }}"
      - "ghcr.io/{{ .Env.XORG }}/{{.ProjectName}}:v{{ .Major }}"
      - "ghcr.io/{{ .Env.XORG }}/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/{{ .Env.XORG }}/{{.ProjectName}}:latest"
    dockerfile: ./tools/release/Dockerfile

nfpms:
  -
    vendor: "{{ .Env.XNAME }}"
    homepage: "{{ .Env.XHOMEPAGE }}"
    maintainer: "{{ .Env.XNAME }} <{{ .Env.XEMAIL }}>"
    description: "{{ .Env.XDESCRIPTION }}"
    license: "{{ .Env.XLICENSE }}"
    replacements: *replacements
    formats:
      - apk
      - deb
      - rpm

scoop:
  bucket:
    owner: "{{ .Env.XORG }}"
    name: "{{ .ProjectName }}"
  commit_author:
    name: "{{ .Env.XNAME }}"
    email: "{{ .Env.XEMAIL }}"
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: "{{ .Env.XHOMEPAGE }}"
  description: "{{ .Env.XSUMMARY }}"
  license: "{{ .Env.XLICENSE }}"
  skip_upload: false

snapcrafts:
  -
    publish: false
    replacements: *replacements
    summary: "{{ .Env.XSUMMARY }}"
    description: "{{ .Env.XDESCRIPTION }}"
    grade: stable
    confinement: strict
    license: "{{{ .License }}}"

builds:
  - id: "darwin_amd64"
    goos:
      - darwin
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
    hooks:
      post:
        - "./bin/build/desktop.release.sh {{ .Version }}"
        - "./bin/build/notarize-amd64.sh {{ .Version }}"
        - "./bin/build/android.sh {{ .Version }}"
        - "./bin/build/ios.sh {{ .Version }}"

  - id: "darwin_arm64"
    goos:
      - darwin
    goarch:
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    hooks:
      post:
        - "./bin/build/notarize-arm64.sh {{ .Version }}"

  - id: "linux"
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "linux-arm"
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 5
      - 6
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
    skip: {{{ .SkipLinuxArm }}}

  - id: "linux-mips"
    goos:
      - linux
    goarch:
      - mips
      - mipsle
      - mips64
      - mips64le
    gomips:
      - hardfloat
      - softfloat
    mod_timestamp: "{{ .CommitTimestamp }}"
    skip: {{{ .SkipLinuxMips }}}

  - id: "linux-odd"
    goos:
      - linux
    goarch:
      - ppc64
      - ppc64le
      - riscv64
      - s390x
    mod_timestamp: "{{ .CommitTimestamp }}"
    skip: {{{ .SkipLinuxOdd }}}


  - id: "windows"
    goos:
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "js"
    goos:
      - js
    goarch:
      - wasm
    mod_timestamp: "{{ .CommitTimestamp }}"
    skip: {{{ .SkipWASM }}}

  - id: "aix"
    goos:
      - aix
    goarch:
      - ppc64
    mod_timestamp: "{{ .CommitTimestamp }}"
    skip: {{{ .SkipAIX }}}

  - id: "dragonfly"
    goos:
      - dragonfly
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
    skip: {{{ .SkipDragonfly }}}

  - id: "illumos"
    goos:
      - illumos
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
    skip: {{{ .SkipIllumos }}}

  - id: "freebsd"
    goos:
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
    skip: {{{ .SkipFreeBSD }}}

  - id: "netbsd"
    goos:
      - netbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
    skip: {{{ .SkipNetBSD }}}

  - id: "openbsd"
    goos:
      - openbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
    skip: {{{ .SkipOpenBSD }}}

  - id: "plan9"
    goos:
      - plan9
    goarch:
      - 386
      - amd64
      - arm
    goarm:
      - 5
      - 6
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
    skip: {{{ .SkipPlan9 }}}

  - id: "solaris"
    goos:
      - solaris
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
    skip: {{{ .SkipSolaris }}}
