# http://goreleaser.com
archives:
  - format: zip
    wrap_in_directory: false
    replacements: &replacements
      darwin: macos
      386: i386
      amd64: x86_64
    files:
      - none*

brews:
  -
    tap:
      owner: "{{{ .Info.Org }}}"
      name: "homebrew-{{{ .Info.Org }}}"
    commit_author:
      name: "{{{ .Info.AuthorName }}}"
      email: "{{{ .Info.AuthorEmail }}}"
    folder: Formula
    homepage: "{{{ .Info.Homepage }}}"
    description: "{{{ .Info.Description }}}"
    license: "{{{ .Info.License }}}"
    skip_upload: {{{ if .Build.Homebrew }}}false{{{ else }}}true{{{ end }}}

changelog:
  skip: true

checksum:
  name_template: "checksums.txt"
  extra_files:{{{ if .Build.Notarize }}}
    - glob: "./build/dist/*_notarized.zip"{{{ end }}}{{{ if .Build.Desktop }}}
    - glob: "./build/dist/*_desktop_*.dmg"
    - glob: "./build/dist/*_desktop_*.zip"{{{ end }}}
    # $PF_SECTION_START(checksums)$
    # $PF_SECTION_END(checksums)$

dockers:
  -
    image_templates:
      - "ghcr.io/{{{ .Info.Org }}}/{{{ .Key }}}:{{ .Major }}"
      - "ghcr.io/{{{ .Info.Org }}}/{{{ .Key }}}:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/{{{ .Info.Org }}}/{{{ .Key }}}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "ghcr.io/{{{ .Info.Org }}}/{{{ .Key }}}:latest"
    dockerfile: ./tools/release/Dockerfile
  -
    image_templates:
      - "ghcr.io/{{{ .Info.Org }}}/{{{ .Key }}}:{{ .Major }}-debug"
      - "ghcr.io/{{{ .Info.Org }}}/{{{ .Key }}}:{{ .Major }}.{{ .Minor }}-debug"
      - "ghcr.io/{{{ .Info.Org }}}/{{{ .Key }}}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-debug"
      - "ghcr.io/{{{ .Info.Org }}}/{{{ .Key }}}:latest-debug"
    dockerfile: ./tools/release/debug.Dockerfile

dist: "build/dist"
{{{ if .Build.NFPMS }}}
nfpms:
  -
    vendor: "{{{ .Info.AuthorName }}}"
    homepage: "{{{ .Info.Homepage }}}}"
    maintainer: "{{{ .Info.AuthorName }}} <{{{ .Info.AuthorEmail }}}>"
    description: "{{{ .Info.Description }}}"
    license: "{{{ .Info.License }}}"
    replacements: *replacements
    formats:
      - apk
      - deb
      - rpm
{{{ end }}}
release:
  draft: {{{ if .Build.Publish }}}false{{{ else }}}true{{{ end }}}
  header: |
    ## {{ .Version }} ({{ .Date }})
    See {{{ .Info.Homepage }}} for download links and documentation
    ## Main downloads
    - [Linux Intel 64 bit]({{{ .Info.Sourcecode }}}/releases/download/{{ .Version }}/{{{ .Key }}}_{{ .Version }}_linux_x86_64.zip)
    - [MacOS Intel 64 bit]({{{ .Info.Sourcecode }}}/releases/download/{{ .Version }}/{{{ .Key }}}_{{ .Version }}_macos_x86_64.zip)
    - [Windows Intel 64 bit]({{{ .Info.Sourcecode }}}/releases/download/{{ .Version }}/{{{ .Key }}}_{{ .Version }}_windows_x86_64.zip)

  extra_files:{{{ if .Build.Notarize }}}
    - glob: "./build/dist/*_notarized.zip"{{{ end }}}{{{ if .Build.Desktop }}}
    - glob: "./build/dist/*.dmg"
    - glob: "./build/dist/*_desktop_*.zip"{{{ end }}}{{{ if .Build.Mobile }}}
    - glob: "./build/dist/*_mobile_*.zip"{{{ end }}}
    # $PF_SECTION_START(releasefiles)$
    # $PF_SECTION_END(releasefiles)$
{{{ if .Build.Signing }}}
signs:
  - artifacts: checksum
{{{ end }}}{{{ if .Build.Snapcraft }}}
snapcrafts:
  -
    publish: false
    replacements: *replacements
    summary: "{{{ .Info.Summary }}}"
    description: "{{{ .Info.Description }}}"
    grade: stable
    confinement: strict
    license: "{{{ .Info.License }}}"
{{{ end }}}
snapshot:
  name_template: "{{ .Tag }}"

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"
  format: "zip"

builds:
  - id: "darwin_amd64"
    goos:
      - darwin
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
    hooks:
      post:{{{ if .Build.Desktop }}}
        - "./bin/build/desktop.release.sh {{ .Version }}"{{{ end }}}{{{ if .Build.Notarize }}}
        - "./tools/notarize/notarize-amd64.sh {{ .Version }}"{{{ end }}}{{{ if .BuildAndroid }}}
        - "./bin/build/android.sh {{ .Version }}"{{{ end }}}{{{ if .BuildIOS }}}
        - "./bin/build/ios.sh {{ .Version }}"{{{ end }}}
        # $PF_SECTION_START(extrascripts)$
        # $PF_SECTION_END(extrascripts)$

  - id: "darwin_arm64"
    goos:
      - darwin
    goarch:
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"{{{ if .Build.Notarize }}}
    hooks:
      post:
        - "./tools/notarize/notarize-arm64.sh {{ .Version }}"{{{ end }}}

  - id: "linux"
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ if .Build.LinuxARM }}}
  - id: "linux-arm"
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 5
      - 6
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ end }}}{{{ if .Build.LinuxMIPS }}}
  - id: "linux-mips"
    goos:
      - linux
    goarch:
      - mips
      - mipsle
      - mips64
      - mips64le
    gomips:
      - hardfloat
      - softfloat
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ end }}}{{{ if .Build.LinuxOdd }}}
  - id: "linux-odd"
    goos:
      - linux
    goarch:
      - ppc64
      - ppc64le
      - riscv64
      - s390x
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ end }}}
  - id: "windows"
    goos:
      - windows
    goarch:
      - 386
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ if .Build.WindowsARM }}}
  - id: "windows-arm"
    goos:
      - windows
    goarch:
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ end }}}{{{ if .Build.WASM }}}
  - id: "js"
    goos:
      - js
    goarch:
      - wasm
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ end }}}{{{ if .Build.AIX }}}
  - id: "aix"
    goos:
      - aix
    goarch:
      - ppc64
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ end }}}{{{ if .Build.Dragonfly }}}
  - id: "dragonfly"
    goos:
      - dragonfly
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ end }}}{{{ if .Build.Illumos }}}
  - id: "illumos"
    goos:
      - illumos
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ end }}}{{{ if .Build.FreeBSD }}}
  - id: "freebsd"
    goos:
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ end }}}{{{ if .Build.NetBSD }}}
  - id: "netbsd"
    goos:
      - netbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ end }}}{{{ if .Build.OpenBSD }}}
  - id: "openbsd"
    goos:
      - openbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ end }}}{{{ if .Build.Plan9 }}}
  - id: "plan9"
    goos:
      - plan9
    goarch:
      - 386
      - amd64
      - arm
    goarm:
      - 5
      - 6
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ end }}}{{{ if .Build.Solaris }}}
  - id: "solaris"
    goos:
      - solaris
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ end -}}}
