# http://goreleaser.com
archives:
  - format: zip
    wrap_in_directory: false
    replacements: &replacements
      darwin: macos
      386: i386
      amd64: x86_64
    files:
      - none*

brews:
  -
    tap:
      owner: "{{{ .Info.Org }}}"
      name: "homebrew-{{{ .Info.Org }}}"
    commit_author:
      name: "{{{ .Info.AuthorName }}}"
      email: "{{{ .Info.AuthorEmail }}}"
    folder: Formula
    homepage: "{{{ .Info.Homepage }}}"
    description: "{{{ .Info.Description }}}"
    license: "{{{ .Info.License }}}"
    skip_upload: {{{ .Build.SkipHomebrew }}}

changelog:
  skip: true

checksum:
  name_template: "checksums.txt"

dockers:
  -
    image_templates:
      - "ghcr.io/{{{ .Info.Org }}}/{{{ .Key }}}:{{ .Tag }}"
      - "ghcr.io/{{{ .Info.Org }}}/{{{ .Key }}}:v{{ .Major }}"
      - "ghcr.io/{{{ .Info.Org }}}/{{{ .Key }}}:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/{{{ .Info.Org }}}/{{{ .Key }}}:latest"
    dockerfile: ./tools/release/Dockerfile

dist: "build/dist"
{{{if .Build.SkipNFPMS}}}{{{else}}}
nfpms:
  -
    vendor: "{{{ .Info.AuthorName }}}"
    homepage: "{{{ .Info.Homepage }}}}"
    maintainer: "{{{ .Info.AuthorName }}} <{{{ .Info.AuthorEmail }}}>"
    description: "{{{ .Info.Description }}}"
    license: "{{{ .Info.License }}}"
    replacements: *replacements
    formats:
      - apk
      - deb
      - rpm
{{{end}}}
release:
  draft: {{{if .Build.SkipPublish}}}true{{{else}}}false{{{ end }}}
  header: |
    ## {{ .Version }} ({{ .Date }})
    See {{{ .Info.Homepage }}} for download links and documentation
    ## Main downloads
    - [Linux Intel 64 bit]({{{ .Info.Sourcecode }}}/releases/download/{{ .Version }}/{{{ .Key }}}_{{ .Version }}_linux_x86_64.zip)
    - [MacOS Intel 64 bit]({{{ .Info.Sourcecode }}}/releases/download/{{ .Version }}/{{{ .Key }}}_{{ .Version }}_macos_x86_64.zip)
    - [Windows Intel 64 bit]({{{ .Info.Sourcecode }}}/releases/download/{{ .Version }}/{{{ .Key }}}_{{ .Version }}_windows_x86_64.zip)

  extra_files:{{{ if .Build.SkipNotarize }}}{{{ else }}}
    - glob: "./build/dist/*_notarized.zip"{{{ end }}}
    - glob: "./build/dist/*.dmg"{{{ if .Build.SkipDesktop }}}{{{ else }}}
    - glob: "./build/dist/*_desktop_*.zip"{{{ end }}}
    - glob: "./build/dist/*_mobile_*.zip"
{{{if .Build.SkipScoop}}}{{{else}}}
scoop:
  bucket:
    owner: "{{{ .Info.Org }}}"
    name: "{{{ .Key }}}"
  commit_author:
    name: "{{{ .Info.AuthorName }}}"
    email: "{{{ .Info.AuthorEmail }}}"
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: "{{{ .Info.Homepage }}}"
  description: "{{{ .Info.Summary }}}"
  license: "{{{ .Info.License }}}"
  skip_upload: false
{{{end}}}{{{if .Build.SkipSigning}}}{{{else}}}
signs:
  - artifacts: checksum
{{{ end }}}{{{if .Build.SkipSnapcraft}}}{{{else}}}
snapcrafts:
  -
    publish: false
    replacements: *replacements
    summary: "{{{ .Info.Summary }}}"
    description: "{{{ .Info.Description }}}"
    grade: stable
    confinement: strict
    license: "{{{ .Info.License }}}"
{{{end}}}
snapshot:
  name_template: "{{ .Tag }}"

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"
  format: "zip"

builds:
  - id: "darwin_amd64"
    goos:
      - darwin
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
    hooks:
      post:{{{ if .Build.SkipDesktop }}}{{{ else }}}
        - "./bin/build/desktop.release.sh {{ .Version }}"{{{ end }}}{{{ if .Build.SkipNotarize }}}{{{ else }}}
        - "./tools/notarize/notarize-amd64.sh {{ .Version }}"{{{ end }}}{{{ if .BuildAndroid }}}
        - "./bin/build/android.sh {{ .Version }}"{{{ end }}}{{{ if .BuildIOS }}}
        - "./bin/build/ios.sh {{ .Version }}"{{{ end }}}

  - id: "darwin_arm64"
    goos:
      - darwin
    goarch:
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"{{{ if .Build.SkipNotarize }}}{{{ else }}}
    hooks:
      post:
        - "./tools/notarize/notarize-arm64.sh {{ .Version }}"{{{ end }}}

  - id: "linux"
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{if .Build.SkipLinuxARM}}}{{{else}}}
  - id: "linux-arm"
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 5
      - 6
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ end }}}{{{if .Build.SkipLinuxMIPS}}}{{{else}}}
  - id: "linux-mips"
    goos:
      - linux
    goarch:
      - mips
      - mipsle
      - mips64
      - mips64le
    gomips:
      - hardfloat
      - softfloat
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ end }}}{{{if .Build.SkipLinuxOdd}}}{{{else}}}
  - id: "linux-odd"
    goos:
      - linux
    goarch:
      - ppc64
      - ppc64le
      - riscv64
      - s390x
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ end }}}
  - id: "windows"
    goos:
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{if .Build.SkipWASM}}}{{{else}}}
  - id: "js"
    goos:
      - js
    goarch:
      - wasm
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ end }}}{{{if .Build.SkipAIX}}}{{{else}}}
  - id: "aix"
    goos:
      - aix
    goarch:
      - ppc64
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ end }}}{{{if .Build.SkipDragonfly}}}{{{else}}}
  - id: "dragonfly"
    goos:
      - dragonfly
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ end }}}{{{if .Build.SkipIllumos}}}{{{else}}}
  - id: "illumos"
    goos:
      - illumos
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ end }}}{{{if .Build.SkipFreeBSD}}}{{{else}}}
  - id: "freebsd"
    goos:
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ end }}}{{{if .Build.SkipNetBSD}}}{{{else}}}
  - id: "netbsd"
    goos:
      - netbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ end }}}{{{if .Build.SkipOpenBSD}}}{{{else}}}
  - id: "openbsd"
    goos:
      - openbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ end }}}{{{if .Build.SkipPlan9}}}{{{else}}}
  - id: "plan9"
    goos:
      - plan9
    goarch:
      - 386
      - amd64
      - arm
    goarm:
      - 5
      - 6
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ end }}}{{{if .Build.SkipSolaris}}}{{{else}}}
  - id: "solaris"
    goos:
      - solaris
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
{{{ end -}}}
