// Code generated by qtc from "Any.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/components/view/Any.html:1
package view

//line views/components/view/Any.html:1
import (
	"encoding/json/jsontext"
	"fmt"
	"net/url"
	"time"

	"github.com/google/uuid"

	"projectforge.dev/projectforge/app/controller/cutil"
	"projectforge.dev/projectforge/app/lib/jsonschema"
	"projectforge.dev/projectforge/app/util"
	"projectforge.dev/projectforge/views/components"
)

//line views/components/view/Any.html:15
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/components/view/Any.html:15
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/components/view/Any.html:15
func StreamAny(qw422016 *qt422016.Writer, x any, ps *cutil.PageState) {
//line views/components/view/Any.html:16
	if x == nil {
//line views/components/view/Any.html:16
		qw422016.N().S(`<em>nil</em>`)
//line views/components/view/Any.html:18
	} else {
//line views/components/view/Any.html:19
		switch t := x.(type) {
//line views/components/view/Any.html:20
		case bool:
//line views/components/view/Any.html:21
			StreamBool(qw422016, t)
//line views/components/view/Any.html:22
		case *bool:
//line views/components/view/Any.html:23
			StreamBool(qw422016, *t)
//line views/components/view/Any.html:24
		case util.Diffs:
//line views/components/view/Any.html:25
			StreamDiffs(qw422016, t)
//line views/components/view/Any.html:26
		case float32:
//line views/components/view/Any.html:27
			StreamFloat(qw422016, t)
//line views/components/view/Any.html:28
		case *float32:
//line views/components/view/Any.html:29
			StreamFloat(qw422016, *t)
//line views/components/view/Any.html:30
		case float64:
//line views/components/view/Any.html:31
			StreamFloat(qw422016, t)
//line views/components/view/Any.html:32
		case *float64:
//line views/components/view/Any.html:33
			StreamFloat(qw422016, *t)
//line views/components/view/Any.html:34
		case int:
//line views/components/view/Any.html:35
			StreamInt(qw422016, t)
//line views/components/view/Any.html:36
		case *int:
//line views/components/view/Any.html:37
			StreamInt(qw422016, *t)
//line views/components/view/Any.html:38
		case int32:
//line views/components/view/Any.html:39
			StreamInt(qw422016, t)
//line views/components/view/Any.html:40
		case *int32:
//line views/components/view/Any.html:41
			StreamInt(qw422016, *t)
//line views/components/view/Any.html:42
		case int64:
//line views/components/view/Any.html:43
			StreamInt(qw422016, t)
//line views/components/view/Any.html:44
		case *int64:
//line views/components/view/Any.html:45
			StreamInt(qw422016, *t)
//line views/components/view/Any.html:46
		case *jsonschema.Schema:
//line views/components/view/Any.html:47
			StreamJSONSchema(qw422016, t, true, ps)
//line views/components/view/Any.html:48
		case jsonschema.Schemas:
//line views/components/view/Any.html:49
			StreamAny(qw422016, util.ArrayToAnyArray(t), ps)
//line views/components/view/Any.html:50
		case jsontext.Value:
//line views/components/view/Any.html:51
			x, _ := util.FromJSONAny(t)

//line views/components/view/Any.html:52
			StreamAny(qw422016, x, ps)
//line views/components/view/Any.html:53
		case util.ToOrderedMap[any]:
//line views/components/view/Any.html:54
			StreamOrderedMap(qw422016, false, t.ToOrderedMap(), ps)
//line views/components/view/Any.html:55
		case *util.OrderedMap[any]:
//line views/components/view/Any.html:56
			StreamOrderedMap(qw422016, false, t, ps)
//line views/components/view/Any.html:57
		case util.ToOrderedMapAny:
//line views/components/view/Any.html:58
			StreamOrderedMap(qw422016, false, t.ToOrderedMapAny(), ps)
//line views/components/view/Any.html:59
		case util.ToOrderedMaps[any]:
//line views/components/view/Any.html:60
			StreamOrderedMapArray(qw422016, false, ps, t.ToOrderedMaps()...)
//line views/components/view/Any.html:61
		case []*util.OrderedMap[any]:
//line views/components/view/Any.html:62
			StreamOrderedMapArray(qw422016, false, ps, t...)
//line views/components/view/Any.html:63
		case map[string]jsontext.Value:
//line views/components/view/Any.html:64
			m, _ := util.FromJSONBytesMap[any](t)

//line views/components/view/Any.html:65
			StreamMap(qw422016, false, m, ps)
//line views/components/view/Any.html:66
		case util.ToMap:
//line views/components/view/Any.html:67
			StreamMap(qw422016, false, t.ToMap(), ps)
//line views/components/view/Any.html:68
		case util.ValueMap:
//line views/components/view/Any.html:69
			StreamMap(qw422016, false, t, ps)
//line views/components/view/Any.html:70
		case map[string]any:
//line views/components/view/Any.html:71
			StreamMap(qw422016, false, t, ps)
//line views/components/view/Any.html:72
		case util.ToMaps:
//line views/components/view/Any.html:73
			StreamMapArray(qw422016, false, ps, t.ToMaps()...)
//line views/components/view/Any.html:74
		case []util.ValueMap:
//line views/components/view/Any.html:75
			StreamMapArray(qw422016, false, ps, t...)
//line views/components/view/Any.html:76
		case util.Pkg:
//line views/components/view/Any.html:77
			StreamPackage(qw422016, t)
//line views/components/view/Any.html:78
		case string:
//line views/components/view/Any.html:79
			StreamString(qw422016, t)
//line views/components/view/Any.html:80
		case *string:
//line views/components/view/Any.html:81
			StreamString(qw422016, *t)
//line views/components/view/Any.html:82
		case []string:
//line views/components/view/Any.html:83
			StreamStringArray(qw422016, t)
//line views/components/view/Any.html:84
		case time.Time:
//line views/components/view/Any.html:85
			StreamTimestamp(qw422016, &t)
//line views/components/view/Any.html:86
		case *time.Time:
//line views/components/view/Any.html:87
			StreamTimestamp(qw422016, t)
//line views/components/view/Any.html:88
		case url.URL:
//line views/components/view/Any.html:89
			StreamURL(qw422016, t, "", true, ps)
//line views/components/view/Any.html:90
		case *url.URL:
//line views/components/view/Any.html:91
			StreamURL(qw422016, *t, "", true, ps)
//line views/components/view/Any.html:92
		case uuid.UUID:
//line views/components/view/Any.html:93
			StreamUUID(qw422016, &t)
//line views/components/view/Any.html:94
		case *uuid.UUID:
//line views/components/view/Any.html:95
			StreamUUID(qw422016, t)
//line views/components/view/Any.html:96
		case []any:
//line views/components/view/Any.html:97
			if len(t) == 0 {
//line views/components/view/Any.html:97
				qw422016.N().S(`<em>empty array</em>`)
//line views/components/view/Any.html:99
			} else {
//line views/components/view/Any.html:100
				arr, extra := util.ArrayLimit(t, 8)

//line views/components/view/Any.html:101
				for idx, e := range arr {
//line views/components/view/Any.html:101
					qw422016.N().S(`<div class="flex bb"><div class="mts mrs mbs"><em>`)
//line views/components/view/Any.html:103
					qw422016.N().D(idx + 1)
//line views/components/view/Any.html:103
					qw422016.N().S(`</em></div><div class="mts mbs full-width">`)
//line views/components/view/Any.html:104
					StreamAny(qw422016, e, ps)
//line views/components/view/Any.html:104
					qw422016.N().S(`</div></div>`)
//line views/components/view/Any.html:106
				}
//line views/components/view/Any.html:107
				if extra > 0 {
//line views/components/view/Any.html:107
					qw422016.N().S(`<div class="mts"><em>...and`)
//line views/components/view/Any.html:108
					qw422016.N().S(` `)
//line views/components/view/Any.html:108
					qw422016.N().D(extra)
//line views/components/view/Any.html:108
					qw422016.N().S(` `)
//line views/components/view/Any.html:108
					qw422016.N().S(`more</em></div>`)
//line views/components/view/Any.html:109
				}
//line views/components/view/Any.html:110
			}
//line views/components/view/Any.html:111
		case fmt.Stringer:
//line views/components/view/Any.html:112
			StreamString(qw422016, t.String())
//line views/components/view/Any.html:113
		default:
//line views/components/view/Any.html:113
			qw422016.N().S(`unhandled type [`)
//line views/components/view/Any.html:114
			qw422016.E().S(fmt.Sprintf("%T", x))
//line views/components/view/Any.html:114
			qw422016.N().S(`]`)
//line views/components/view/Any.html:115
		}
//line views/components/view/Any.html:116
	}
//line views/components/view/Any.html:117
}

//line views/components/view/Any.html:117
func WriteAny(qq422016 qtio422016.Writer, x any, ps *cutil.PageState) {
//line views/components/view/Any.html:117
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/view/Any.html:117
	StreamAny(qw422016, x, ps)
//line views/components/view/Any.html:117
	qt422016.ReleaseWriter(qw422016)
//line views/components/view/Any.html:117
}

//line views/components/view/Any.html:117
func Any(x any, ps *cutil.PageState) string {
//line views/components/view/Any.html:117
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/view/Any.html:117
	WriteAny(qb422016, x, ps)
//line views/components/view/Any.html:117
	qs422016 := string(qb422016.B)
//line views/components/view/Any.html:117
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/view/Any.html:117
	return qs422016
//line views/components/view/Any.html:117
}

//line views/components/view/Any.html:119
func StreamAnyTable(qw422016 *qt422016.Writer, title string, value any, indent int, ps *cutil.PageState) {
//line views/components/view/Any.html:119
	qw422016.N().S(`<tr>`)
//line views/components/view/Any.html:121
	components.StreamIndent(qw422016, true, indent+1)
//line views/components/view/Any.html:121
	qw422016.N().S(`<th class="shrink">`)
//line views/components/view/Any.html:122
	qw422016.E().S(title)
//line views/components/view/Any.html:122
	qw422016.N().S(`</th>`)
//line views/components/view/Any.html:123
	components.StreamIndent(qw422016, true, indent+1)
//line views/components/view/Any.html:123
	qw422016.N().S(`<td>`)
//line views/components/view/Any.html:124
	StreamAny(qw422016, value, ps)
//line views/components/view/Any.html:124
	qw422016.N().S(`</td>`)
//line views/components/view/Any.html:125
	components.StreamIndent(qw422016, true, indent)
//line views/components/view/Any.html:125
	qw422016.N().S(`</tr>`)
//line views/components/view/Any.html:127
}

//line views/components/view/Any.html:127
func WriteAnyTable(qq422016 qtio422016.Writer, title string, value any, indent int, ps *cutil.PageState) {
//line views/components/view/Any.html:127
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/view/Any.html:127
	StreamAnyTable(qw422016, title, value, indent, ps)
//line views/components/view/Any.html:127
	qt422016.ReleaseWriter(qw422016)
//line views/components/view/Any.html:127
}

//line views/components/view/Any.html:127
func AnyTable(title string, value any, indent int, ps *cutil.PageState) string {
//line views/components/view/Any.html:127
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/view/Any.html:127
	WriteAnyTable(qb422016, title, value, indent, ps)
//line views/components/view/Any.html:127
	qs422016 := string(qb422016.B)
//line views/components/view/Any.html:127
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/view/Any.html:127
	return qs422016
//line views/components/view/Any.html:127
}
