// Code generated by qtc from "Settings.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Code generated by Project Forge, see https://projectforge.dev for details. -->

//line views/vsettings/Settings.html:2
package vsettings

//line views/vsettings/Settings.html:2
import (
	"github.com/kyleu/projectforge/app"
	"github.com/kyleu/projectforge/app/controller/cutil"
	"github.com/kyleu/projectforge/app/settings"
	"github.com/kyleu/projectforge/app/user"
	"github.com/kyleu/projectforge/views/components"
	"github.com/kyleu/projectforge/views/layout"
	"github.com/kyleu/projectforge/views/vauth"
)

//line views/vsettings/Settings.html:12
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vsettings/Settings.html:12
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vsettings/Settings.html:12
type Settings struct {
	layout.Basic
	Settings *settings.Settings
	Perms    user.Permissions
}

//line views/vsettings/Settings.html:18
func (p *Settings) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vsettings/Settings.html:18
	qw422016.N().S(`
  `)
//line views/vsettings/Settings.html:19
	StreamAbout(qw422016, as)
//line views/vsettings/Settings.html:19
	qw422016.N().S(`
  <div class="card">
    <div class="right"><a href="#modal-settings"><button type="button">JSON</button></a></div>
    <h3>Settings</h3>
  </div>
  <div class="card">
    <h3>Themes</h3>
    <p><a href="/theme">Edit Themes</a></p>
  </div>
  `)
//line views/vsettings/Settings.html:28
	vauth.StreamAuthentication(qw422016, as)
//line views/vsettings/Settings.html:28
	qw422016.N().S(`
  `)
//line views/vsettings/Settings.html:29
	vauth.StreamPermissions(qw422016, p.Perms, as)
//line views/vsettings/Settings.html:29
	qw422016.N().S(`
  `)
//line views/vsettings/Settings.html:30
	components.StreamJSONModal(qw422016, "settings", "Settings JSON", p.Settings, 1)
//line views/vsettings/Settings.html:30
	qw422016.N().S(`
`)
//line views/vsettings/Settings.html:31
}

//line views/vsettings/Settings.html:31
func (p *Settings) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vsettings/Settings.html:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vsettings/Settings.html:31
	p.StreamBody(qw422016, as, ps)
//line views/vsettings/Settings.html:31
	qt422016.ReleaseWriter(qw422016)
//line views/vsettings/Settings.html:31
}

//line views/vsettings/Settings.html:31
func (p *Settings) Body(as *app.State, ps *cutil.PageState) string {
//line views/vsettings/Settings.html:31
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vsettings/Settings.html:31
	p.WriteBody(qb422016, as, ps)
//line views/vsettings/Settings.html:31
	qs422016 := string(qb422016.B)
//line views/vsettings/Settings.html:31
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vsettings/Settings.html:31
	return qs422016
//line views/vsettings/Settings.html:31
}
