// Code generated by qtc from "ModelDetail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vexport/ModelDetail.html:1
package vexport

//line views/vexport/ModelDetail.html:1
import (
	"strings"

	"projectforge.dev/projectforge/app"
	"projectforge.dev/projectforge/app/controller/cutil"
	"projectforge.dev/projectforge/app/file"
	"projectforge.dev/projectforge/app/lib/metamodel/model"
	"projectforge.dev/projectforge/views/components"
	"projectforge.dev/projectforge/views/components/view"
	"projectforge.dev/projectforge/views/layout"
)

//line views/vexport/ModelDetail.html:13
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vexport/ModelDetail.html:13
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vexport/ModelDetail.html:13
type ModelDetail struct {
	layout.Basic
	BaseURL string
	Model   *model.Model
	Files   file.Files
}

//line views/vexport/ModelDetail.html:20
func (p *ModelDetail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vexport/ModelDetail.html:20
	qw422016.N().S(`
`)
//line views/vexport/ModelDetail.html:21
	m := p.Model

//line views/vexport/ModelDetail.html:21
	qw422016.N().S(`  <div class="card">
    <div class="right">
      <a href="`)
//line views/vexport/ModelDetail.html:24
	qw422016.E().S(p.BaseURL)
//line views/vexport/ModelDetail.html:24
	qw422016.N().S(`/`)
//line views/vexport/ModelDetail.html:24
	qw422016.E().S(p.Model.Name)
//line views/vexport/ModelDetail.html:24
	qw422016.N().S(`/jsonschema"><button>`)
//line views/vexport/ModelDetail.html:24
	components.StreamSVGButton(qw422016, "table", ps)
//line views/vexport/ModelDetail.html:24
	qw422016.N().S(` JSON Schema</button></a>
      <a href="`)
//line views/vexport/ModelDetail.html:25
	qw422016.E().S(p.BaseURL)
//line views/vexport/ModelDetail.html:25
	qw422016.N().S(`/`)
//line views/vexport/ModelDetail.html:25
	qw422016.E().S(p.Model.Name)
//line views/vexport/ModelDetail.html:25
	qw422016.N().S(`/edit"><button>`)
//line views/vexport/ModelDetail.html:25
	components.StreamSVGButton(qw422016, "edit", ps)
//line views/vexport/ModelDetail.html:25
	qw422016.N().S(` Edit</button></a>
    </div>
    <h3>`)
//line views/vexport/ModelDetail.html:27
	components.StreamSVGIcon(qw422016, m.IconSafe(), ps)
//line views/vexport/ModelDetail.html:27
	qw422016.N().S(` `)
//line views/vexport/ModelDetail.html:27
	qw422016.E().S(m.Name)
//line views/vexport/ModelDetail.html:27
	qw422016.N().S(`</h3>
    <em>export model</em>
    `)
//line views/vexport/ModelDetail.html:29
	streammodelSummary(qw422016, p.BaseURL, m, as, ps)
//line views/vexport/ModelDetail.html:29
	qw422016.N().S(`
  </div>
  <div class="card">
    <h3>`)
//line views/vexport/ModelDetail.html:32
	components.StreamSVGIcon(qw422016, `first-aid`, ps)
//line views/vexport/ModelDetail.html:32
	qw422016.N().S(` Columns</h3>
    `)
//line views/vexport/ModelDetail.html:33
	streammodelColumns(qw422016, m, as, ps)
//line views/vexport/ModelDetail.html:33
	qw422016.N().S(`
  </div>
`)
//line views/vexport/ModelDetail.html:35
	if len(m.Relations) > 0 {
//line views/vexport/ModelDetail.html:35
		qw422016.N().S(`  <div class="card">
    <h3>`)
//line views/vexport/ModelDetail.html:37
		components.StreamSVGIcon(qw422016, `social`, ps)
//line views/vexport/ModelDetail.html:37
		qw422016.N().S(` Relations</h3>
    `)
//line views/vexport/ModelDetail.html:38
		streammodelRelations(qw422016, m, p.BaseURL, as, ps)
//line views/vexport/ModelDetail.html:38
		qw422016.N().S(`
  </div>`)
//line views/vexport/ModelDetail.html:39
	}
//line views/vexport/ModelDetail.html:39
	if len(m.Links) > 0 {
//line views/vexport/ModelDetail.html:39
		qw422016.N().S(`  <div class="card">
    <h3>`)
//line views/vexport/ModelDetail.html:41
		components.StreamSVGIcon(qw422016, `link`, ps)
//line views/vexport/ModelDetail.html:41
		qw422016.N().S(` Links</h3>
    `)
//line views/vexport/ModelDetail.html:42
		streammodelLinks(qw422016, m, as, ps)
//line views/vexport/ModelDetail.html:42
		qw422016.N().S(`
  </div>`)
//line views/vexport/ModelDetail.html:43
	}
//line views/vexport/ModelDetail.html:43
	if len(m.Indexes) > 0 {
//line views/vexport/ModelDetail.html:43
		qw422016.N().S(`  <div class="card">
    <h3>`)
//line views/vexport/ModelDetail.html:45
		components.StreamSVGIcon(qw422016, `star`, ps)
//line views/vexport/ModelDetail.html:45
		qw422016.N().S(` Indexes</h3>
    `)
//line views/vexport/ModelDetail.html:46
		streammodelIndexes(qw422016, m, as, ps)
//line views/vexport/ModelDetail.html:46
		qw422016.N().S(`
  </div>`)
//line views/vexport/ModelDetail.html:47
	}
//line views/vexport/ModelDetail.html:47
	if len(p.Files) > 0 {
//line views/vexport/ModelDetail.html:47
		qw422016.N().S(`  <div class="card">
    <h3>`)
//line views/vexport/ModelDetail.html:49
		components.StreamSVGIcon(qw422016, `file`, ps)
//line views/vexport/ModelDetail.html:49
		qw422016.N().S(` Exported Files</h3>
    `)
//line views/vexport/ModelDetail.html:50
		streammodelFiles(qw422016, m, p.Files, as, ps)
//line views/vexport/ModelDetail.html:50
		qw422016.N().S(`
  </div>`)
//line views/vexport/ModelDetail.html:51
	}
//line views/vexport/ModelDetail.html:52
}

//line views/vexport/ModelDetail.html:52
func (p *ModelDetail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vexport/ModelDetail.html:52
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vexport/ModelDetail.html:52
	p.StreamBody(qw422016, as, ps)
//line views/vexport/ModelDetail.html:52
	qt422016.ReleaseWriter(qw422016)
//line views/vexport/ModelDetail.html:52
}

//line views/vexport/ModelDetail.html:52
func (p *ModelDetail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vexport/ModelDetail.html:52
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vexport/ModelDetail.html:52
	p.WriteBody(qb422016, as, ps)
//line views/vexport/ModelDetail.html:52
	qs422016 := string(qb422016.B)
//line views/vexport/ModelDetail.html:52
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vexport/ModelDetail.html:52
	return qs422016
//line views/vexport/ModelDetail.html:52
}

//line views/vexport/ModelDetail.html:54
func streammodelSummary(qw422016 *qt422016.Writer, baseURL string, model *model.Model, as *app.State, ps *cutil.PageState) {
//line views/vexport/ModelDetail.html:54
	qw422016.N().S(`
  <div class="overflow full-width">
    <table class="mt min-200 full-width">
      <tbody>
        <tr><th class="shrink">Name</th><td>`)
//line views/vexport/ModelDetail.html:58
	qw422016.E().S(model.Name)
//line views/vexport/ModelDetail.html:58
	qw422016.N().S(`</td></tr>
        <tr><th>Package</th><td>`)
//line views/vexport/ModelDetail.html:59
	qw422016.E().S(model.Package)
//line views/vexport/ModelDetail.html:59
	qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:60
	if len(model.Group) > 0 {
//line views/vexport/ModelDetail.html:60
		qw422016.N().S(`        <tr><th>Group</th><td>`)
//line views/vexport/ModelDetail.html:61
		qw422016.E().S(strings.Join(model.Group, "/"))
//line views/vexport/ModelDetail.html:61
		qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:62
	}
//line views/vexport/ModelDetail.html:63
	if model.Schema != "" {
//line views/vexport/ModelDetail.html:63
		qw422016.N().S(`        <tr><th>Schema</th><td>`)
//line views/vexport/ModelDetail.html:64
		qw422016.E().S(model.Schema)
//line views/vexport/ModelDetail.html:64
		qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:65
	}
//line views/vexport/ModelDetail.html:65
	qw422016.N().S(`        <tr><th>Description</th><td>`)
//line views/vexport/ModelDetail.html:66
	qw422016.E().S(model.Description)
//line views/vexport/ModelDetail.html:66
	qw422016.N().S(`</td></tr>
        <tr>
          <th>Ordering</th>
          <td>
`)
//line views/vexport/ModelDetail.html:70
	for _, x := range model.Ordering {
//line views/vexport/ModelDetail.html:70
		qw422016.N().S(`            <div>`)
//line views/vexport/ModelDetail.html:71
		qw422016.E().S(x.String())
//line views/vexport/ModelDetail.html:71
		qw422016.N().S(`</div>
`)
//line views/vexport/ModelDetail.html:72
	}
//line views/vexport/ModelDetail.html:72
	qw422016.N().S(`          </td>
        </tr>
`)
//line views/vexport/ModelDetail.html:75
	if model.SortIndex != 0 {
//line views/vexport/ModelDetail.html:75
		qw422016.N().S(`        <tr><th>Sort Index</th><td>`)
//line views/vexport/ModelDetail.html:76
		qw422016.N().D(model.SortIndex)
//line views/vexport/ModelDetail.html:76
		qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:77
	}
//line views/vexport/ModelDetail.html:78
	if model.TitleOverride != "" {
//line views/vexport/ModelDetail.html:78
		qw422016.N().S(`        <tr><th>Title Override</th><td>`)
//line views/vexport/ModelDetail.html:79
		qw422016.E().S(model.TitleOverride)
//line views/vexport/ModelDetail.html:79
		qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:80
	}
//line views/vexport/ModelDetail.html:81
	if model.PluralOverride != "" {
//line views/vexport/ModelDetail.html:81
		qw422016.N().S(`        <tr><th>Plural Override</th><td>`)
//line views/vexport/ModelDetail.html:82
		qw422016.E().S(model.PluralOverride)
//line views/vexport/ModelDetail.html:82
		qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:83
	}
//line views/vexport/ModelDetail.html:84
	if model.ProperOverride != "" {
//line views/vexport/ModelDetail.html:84
		qw422016.N().S(`        <tr><th>Proper Override</th><td>`)
//line views/vexport/ModelDetail.html:85
		qw422016.E().S(model.ProperOverride)
//line views/vexport/ModelDetail.html:85
		qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:86
	}
//line views/vexport/ModelDetail.html:87
	if model.TableOverride != "" {
//line views/vexport/ModelDetail.html:87
		qw422016.N().S(`        <tr><th>Table Override</th><td>`)
//line views/vexport/ModelDetail.html:88
		qw422016.E().S(model.TableOverride)
//line views/vexport/ModelDetail.html:88
		qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:89
	}
//line views/vexport/ModelDetail.html:90
	if model.RouteOverride != "" {
//line views/vexport/ModelDetail.html:90
		qw422016.N().S(`        <tr><th>Route Override</th><td>`)
//line views/vexport/ModelDetail.html:91
		qw422016.E().S(model.RouteOverride)
//line views/vexport/ModelDetail.html:91
		qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:92
	}
//line views/vexport/ModelDetail.html:93
	if len(model.Tags) > 0 {
//line views/vexport/ModelDetail.html:93
		qw422016.N().S(`        <tr><th>Tags</th><td>`)
//line views/vexport/ModelDetail.html:94
		qw422016.E().S(strings.Join(model.Tags, ", "))
//line views/vexport/ModelDetail.html:94
		qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:95
	}
//line views/vexport/ModelDetail.html:96
	if model.View != "" {
//line views/vexport/ModelDetail.html:96
		qw422016.N().S(`        <tr><th>View</th><td>`)
//line views/vexport/ModelDetail.html:97
		qw422016.E().S(model.View)
//line views/vexport/ModelDetail.html:97
		qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:98
	}
//line views/vexport/ModelDetail.html:99
	if len(model.Search) > 0 {
//line views/vexport/ModelDetail.html:99
		qw422016.N().S(`        <tr><th>Search</th><td>`)
//line views/vexport/ModelDetail.html:100
		qw422016.E().S(strings.Join(model.Search, ", "))
//line views/vexport/ModelDetail.html:100
		qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:101
	}
//line views/vexport/ModelDetail.html:102
	if len(model.SeedData) > 0 {
//line views/vexport/ModelDetail.html:102
		qw422016.N().S(`        <tr><th>Seed Data</th><td><a href="`)
//line views/vexport/ModelDetail.html:103
		qw422016.E().S(baseURL)
//line views/vexport/ModelDetail.html:103
		qw422016.N().S(`/`)
//line views/vexport/ModelDetail.html:103
		qw422016.E().S(model.Name)
//line views/vexport/ModelDetail.html:103
		qw422016.N().S(`/seeddata">`)
//line views/vexport/ModelDetail.html:103
		qw422016.N().D(len(model.SeedData))
//line views/vexport/ModelDetail.html:103
		qw422016.N().S(` rows</a></td></tr>
`)
//line views/vexport/ModelDetail.html:104
	}
//line views/vexport/ModelDetail.html:105
	if len(model.Config) > 0 {
//line views/vexport/ModelDetail.html:105
		qw422016.N().S(`        <tr><th>Config</th><td>`)
//line views/vexport/ModelDetail.html:106
		view.StreamMap(qw422016, true, model.Config, ps)
//line views/vexport/ModelDetail.html:106
		qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:107
	}
//line views/vexport/ModelDetail.html:108
	if len(model.Links) > 0 {
//line views/vexport/ModelDetail.html:108
		qw422016.N().S(`        <tr><th>Links</th><td>`)
//line views/vexport/ModelDetail.html:109
		components.StreamJSON(qw422016, model.Links)
//line views/vexport/ModelDetail.html:109
		qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:110
	}
//line views/vexport/ModelDetail.html:111
	if len(model.Imports) > 0 {
//line views/vexport/ModelDetail.html:111
		qw422016.N().S(`        <tr><th>Imports</th><td>`)
//line views/vexport/ModelDetail.html:112
		components.StreamJSON(qw422016, model.Imports)
//line views/vexport/ModelDetail.html:112
		qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:113
	}
//line views/vexport/ModelDetail.html:113
	qw422016.N().S(`      </tbody>
    </table>
  </div>
`)
//line views/vexport/ModelDetail.html:117
}

//line views/vexport/ModelDetail.html:117
func writemodelSummary(qq422016 qtio422016.Writer, baseURL string, model *model.Model, as *app.State, ps *cutil.PageState) {
//line views/vexport/ModelDetail.html:117
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vexport/ModelDetail.html:117
	streammodelSummary(qw422016, baseURL, model, as, ps)
//line views/vexport/ModelDetail.html:117
	qt422016.ReleaseWriter(qw422016)
//line views/vexport/ModelDetail.html:117
}

//line views/vexport/ModelDetail.html:117
func modelSummary(baseURL string, model *model.Model, as *app.State, ps *cutil.PageState) string {
//line views/vexport/ModelDetail.html:117
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vexport/ModelDetail.html:117
	writemodelSummary(qb422016, baseURL, model, as, ps)
//line views/vexport/ModelDetail.html:117
	qs422016 := string(qb422016.B)
//line views/vexport/ModelDetail.html:117
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vexport/ModelDetail.html:117
	return qs422016
//line views/vexport/ModelDetail.html:117
}

//line views/vexport/ModelDetail.html:119
func streammodelColumns(qw422016 *qt422016.Writer, model *model.Model, as *app.State, ps *cutil.PageState) {
//line views/vexport/ModelDetail.html:119
	qw422016.N().S(`
`)
//line views/vexport/ModelDetail.html:120
	if len(model.Columns) == 0 {
//line views/vexport/ModelDetail.html:120
		qw422016.N().S(`  <p><em>no columns</em></p>
`)
//line views/vexport/ModelDetail.html:122
	} else {
//line views/vexport/ModelDetail.html:122
		qw422016.N().S(`  <div class="overflow full-width">
    <table class="mt min-200 full-width">
      <thead>
        <tr>
          <th class="shrink">Name</th>
          <th>Type</th>
          <th>Format</th>
          <th>Example</th>
          <th>JSON</th>
          <th>Validation</th>
          <th>Indexed</th>
          <th>Unique</th>
          <th>Tags</th>
          <th>Metadata</th>
        </tr>
      </thead>
      <tbody>
`)
//line views/vexport/ModelDetail.html:140
		for _, col := range model.Columns {
//line views/vexport/ModelDetail.html:140
			qw422016.N().S(`        <tr>
          <td>`)
//line views/vexport/ModelDetail.html:142
			qw422016.E().S(col.Name)
//line views/vexport/ModelDetail.html:142
			qw422016.N().S(`</td>
          <td>`)
//line views/vexport/ModelDetail.html:143
			qw422016.E().S(col.Type.String())
//line views/vexport/ModelDetail.html:143
			qw422016.N().S(`</td>
          <td>`)
//line views/vexport/ModelDetail.html:144
			qw422016.E().S(col.Format)
//line views/vexport/ModelDetail.html:144
			qw422016.N().S(`</td>
          <td>`)
//line views/vexport/ModelDetail.html:145
			qw422016.E().S(col.Example)
//line views/vexport/ModelDetail.html:145
			qw422016.N().S(`</td>
          <td>`)
//line views/vexport/ModelDetail.html:146
			qw422016.E().S(col.JSON)
//line views/vexport/ModelDetail.html:146
			qw422016.N().S(`</td>
          <td>`)
//line views/vexport/ModelDetail.html:147
			qw422016.E().S(col.Validation)
//line views/vexport/ModelDetail.html:147
			qw422016.N().S(`</td>
          <td>`)
//line views/vexport/ModelDetail.html:148
			view.StreamBoolIcon(qw422016, col.Indexed || model.Relations.ContainsSource(col.Name), 15, "icon", ps)
//line views/vexport/ModelDetail.html:148
			qw422016.N().S(`</td>
          <td>`)
//line views/vexport/ModelDetail.html:149
			view.StreamBoolIcon(qw422016, col.HasTag("unique"), 15, "icon", ps)
//line views/vexport/ModelDetail.html:149
			qw422016.N().S(`</td>
          <td>`)
//line views/vexport/ModelDetail.html:150
			qw422016.E().S(strings.Join(col.Tags, ", "))
//line views/vexport/ModelDetail.html:150
			qw422016.N().S(`</td>
          <td>`)
//line views/vexport/ModelDetail.html:151
			view.StreamMap(qw422016, false, col.Metadata, ps)
//line views/vexport/ModelDetail.html:151
			qw422016.N().S(`</td>
        </tr>
`)
//line views/vexport/ModelDetail.html:153
		}
//line views/vexport/ModelDetail.html:153
		qw422016.N().S(`      </tbody>
    </table>
  </div>
`)
//line views/vexport/ModelDetail.html:157
	}
//line views/vexport/ModelDetail.html:158
}

//line views/vexport/ModelDetail.html:158
func writemodelColumns(qq422016 qtio422016.Writer, model *model.Model, as *app.State, ps *cutil.PageState) {
//line views/vexport/ModelDetail.html:158
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vexport/ModelDetail.html:158
	streammodelColumns(qw422016, model, as, ps)
//line views/vexport/ModelDetail.html:158
	qt422016.ReleaseWriter(qw422016)
//line views/vexport/ModelDetail.html:158
}

//line views/vexport/ModelDetail.html:158
func modelColumns(model *model.Model, as *app.State, ps *cutil.PageState) string {
//line views/vexport/ModelDetail.html:158
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vexport/ModelDetail.html:158
	writemodelColumns(qb422016, model, as, ps)
//line views/vexport/ModelDetail.html:158
	qs422016 := string(qb422016.B)
//line views/vexport/ModelDetail.html:158
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vexport/ModelDetail.html:158
	return qs422016
//line views/vexport/ModelDetail.html:158
}

//line views/vexport/ModelDetail.html:160
func streammodelRelations(qw422016 *qt422016.Writer, model *model.Model, baseURL string, as *app.State, ps *cutil.PageState) {
//line views/vexport/ModelDetail.html:160
	qw422016.N().S(`
  <div class="overflow full-width">
    <table class="mt min-200 full-width">
      <thead>
        <tr>
          <th class="shrink">Name</th>
          <th>Source</th>
          <th>Table</th>
          <th>Target</th>
        </tr>
      </thead>
      <tbody>
`)
//line views/vexport/ModelDetail.html:172
	for _, rel := range model.Relations {
//line views/vexport/ModelDetail.html:172
		qw422016.N().S(`        <tr>
          <td>`)
//line views/vexport/ModelDetail.html:174
		qw422016.E().S(rel.Name)
//line views/vexport/ModelDetail.html:174
		qw422016.N().S(`</td>
          <td>`)
//line views/vexport/ModelDetail.html:175
		qw422016.E().S(strings.Join(rel.Src, ", "))
//line views/vexport/ModelDetail.html:175
		qw422016.N().S(`</td>
          <td><a href="`)
//line views/vexport/ModelDetail.html:176
		qw422016.E().S(baseURL)
//line views/vexport/ModelDetail.html:176
		qw422016.N().S(`/`)
//line views/vexport/ModelDetail.html:176
		qw422016.E().S(rel.Table)
//line views/vexport/ModelDetail.html:176
		qw422016.N().S(`">`)
//line views/vexport/ModelDetail.html:176
		qw422016.E().S(rel.Table)
//line views/vexport/ModelDetail.html:176
		qw422016.N().S(`</a></td>
          <td>`)
//line views/vexport/ModelDetail.html:177
		qw422016.E().S(strings.Join(rel.Tgt, ", "))
//line views/vexport/ModelDetail.html:177
		qw422016.N().S(`</td>
        </tr>
`)
//line views/vexport/ModelDetail.html:179
	}
//line views/vexport/ModelDetail.html:179
	qw422016.N().S(`      </tbody>
    </table>
  </div>
`)
//line views/vexport/ModelDetail.html:183
}

//line views/vexport/ModelDetail.html:183
func writemodelRelations(qq422016 qtio422016.Writer, model *model.Model, baseURL string, as *app.State, ps *cutil.PageState) {
//line views/vexport/ModelDetail.html:183
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vexport/ModelDetail.html:183
	streammodelRelations(qw422016, model, baseURL, as, ps)
//line views/vexport/ModelDetail.html:183
	qt422016.ReleaseWriter(qw422016)
//line views/vexport/ModelDetail.html:183
}

//line views/vexport/ModelDetail.html:183
func modelRelations(model *model.Model, baseURL string, as *app.State, ps *cutil.PageState) string {
//line views/vexport/ModelDetail.html:183
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vexport/ModelDetail.html:183
	writemodelRelations(qb422016, model, baseURL, as, ps)
//line views/vexport/ModelDetail.html:183
	qs422016 := string(qb422016.B)
//line views/vexport/ModelDetail.html:183
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vexport/ModelDetail.html:183
	return qs422016
//line views/vexport/ModelDetail.html:183
}

//line views/vexport/ModelDetail.html:185
func streammodelIndexes(qw422016 *qt422016.Writer, model *model.Model, as *app.State, ps *cutil.PageState) {
//line views/vexport/ModelDetail.html:185
	qw422016.N().S(`
  <div class="overflow full-width">
    <table class="mt min-200 full-width">
      <thead>
        <tr>
          <th class="shrink">Name</th>
          <th>Declaration</th>
        </tr>
      </thead>
      <tbody>
`)
//line views/vexport/ModelDetail.html:195
	for _, idx := range model.Indexes {
//line views/vexport/ModelDetail.html:195
		qw422016.N().S(`        <tr>
          <td>`)
//line views/vexport/ModelDetail.html:197
		qw422016.E().S(idx.Name)
//line views/vexport/ModelDetail.html:197
		qw422016.N().S(`</td>
          <td>`)
//line views/vexport/ModelDetail.html:198
		qw422016.E().S(idx.Decl)
//line views/vexport/ModelDetail.html:198
		qw422016.N().S(`</td>
        </tr>
`)
//line views/vexport/ModelDetail.html:200
	}
//line views/vexport/ModelDetail.html:200
	qw422016.N().S(`      </tbody>
    </table>
  </div>
`)
//line views/vexport/ModelDetail.html:204
}

//line views/vexport/ModelDetail.html:204
func writemodelIndexes(qq422016 qtio422016.Writer, model *model.Model, as *app.State, ps *cutil.PageState) {
//line views/vexport/ModelDetail.html:204
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vexport/ModelDetail.html:204
	streammodelIndexes(qw422016, model, as, ps)
//line views/vexport/ModelDetail.html:204
	qt422016.ReleaseWriter(qw422016)
//line views/vexport/ModelDetail.html:204
}

//line views/vexport/ModelDetail.html:204
func modelIndexes(model *model.Model, as *app.State, ps *cutil.PageState) string {
//line views/vexport/ModelDetail.html:204
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vexport/ModelDetail.html:204
	writemodelIndexes(qb422016, model, as, ps)
//line views/vexport/ModelDetail.html:204
	qs422016 := string(qb422016.B)
//line views/vexport/ModelDetail.html:204
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vexport/ModelDetail.html:204
	return qs422016
//line views/vexport/ModelDetail.html:204
}

//line views/vexport/ModelDetail.html:206
func streammodelLinks(qw422016 *qt422016.Writer, model *model.Model, as *app.State, ps *cutil.PageState) {
//line views/vexport/ModelDetail.html:206
	qw422016.N().S(`
  <div class="overflow full-width">
    <table class="mt min-200 full-width">
      <thead>
        <tr>
          <th class="shrink">Title</th>
          <th>URL</th>
          <th>Icon</th>
          <th>Tags</th>
        </tr>
      </thead>
      <tbody>
`)
//line views/vexport/ModelDetail.html:218
	for _, l := range model.Links {
//line views/vexport/ModelDetail.html:218
		qw422016.N().S(`        <tr>
          <td>`)
//line views/vexport/ModelDetail.html:220
		qw422016.E().S(l.Title)
//line views/vexport/ModelDetail.html:220
		qw422016.N().S(`</td>
          <td>`)
//line views/vexport/ModelDetail.html:221
		view.StreamURL(qw422016, l.URL, "", true, ps)
//line views/vexport/ModelDetail.html:221
		qw422016.N().S(`</td>
          <td>`)
//line views/vexport/ModelDetail.html:222
		components.StreamSVGIcon(qw422016, l.Icon, ps)
//line views/vexport/ModelDetail.html:222
		qw422016.N().S(`</td>
          <td>`)
//line views/vexport/ModelDetail.html:223
		view.StreamStringArray(qw422016, l.Tags)
//line views/vexport/ModelDetail.html:223
		qw422016.N().S(`</td>
        </tr>
`)
//line views/vexport/ModelDetail.html:225
	}
//line views/vexport/ModelDetail.html:225
	qw422016.N().S(`      </tbody>
    </table>
  </div>
`)
//line views/vexport/ModelDetail.html:229
}

//line views/vexport/ModelDetail.html:229
func writemodelLinks(qq422016 qtio422016.Writer, model *model.Model, as *app.State, ps *cutil.PageState) {
//line views/vexport/ModelDetail.html:229
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vexport/ModelDetail.html:229
	streammodelLinks(qw422016, model, as, ps)
//line views/vexport/ModelDetail.html:229
	qt422016.ReleaseWriter(qw422016)
//line views/vexport/ModelDetail.html:229
}

//line views/vexport/ModelDetail.html:229
func modelLinks(model *model.Model, as *app.State, ps *cutil.PageState) string {
//line views/vexport/ModelDetail.html:229
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vexport/ModelDetail.html:229
	writemodelLinks(qb422016, model, as, ps)
//line views/vexport/ModelDetail.html:229
	qs422016 := string(qb422016.B)
//line views/vexport/ModelDetail.html:229
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vexport/ModelDetail.html:229
	return qs422016
//line views/vexport/ModelDetail.html:229
}

//line views/vexport/ModelDetail.html:231
func streammodelFiles(qw422016 *qt422016.Writer, model *model.Model, fls file.Files, as *app.State, ps *cutil.PageState) {
//line views/vexport/ModelDetail.html:231
	qw422016.N().S(`
  <div class="mt">
    <ul class="accordion">
`)
//line views/vexport/ModelDetail.html:234
	for _, f := range fls {
//line views/vexport/ModelDetail.html:234
		qw422016.N().S(`      <li>
        <input id="accordion-`)
//line views/vexport/ModelDetail.html:236
		qw422016.E().S(f.FullPath())
//line views/vexport/ModelDetail.html:236
		qw422016.N().S(`" type="checkbox" hidden />
        <label for="accordion-`)
//line views/vexport/ModelDetail.html:237
		qw422016.E().S(f.FullPath())
//line views/vexport/ModelDetail.html:237
		qw422016.N().S(`">`)
//line views/vexport/ModelDetail.html:237
		components.StreamExpandCollapse(qw422016, 3, ps)
//line views/vexport/ModelDetail.html:237
		qw422016.N().S(` `)
//line views/vexport/ModelDetail.html:237
		qw422016.E().S(f.FullPath())
//line views/vexport/ModelDetail.html:237
		qw422016.N().S(`</label>
        <div class="bd"><div><div>
`)
//line views/vexport/ModelDetail.html:239
		out, err := cutil.FormatLang(f.Content, f.Ext())

//line views/vexport/ModelDetail.html:239
		qw422016.N().S(`          `)
//line views/vexport/ModelDetail.html:240
		if err == nil {
//line views/vexport/ModelDetail.html:240
			qw422016.N().S(out)
//line views/vexport/ModelDetail.html:240
		} else {
//line views/vexport/ModelDetail.html:240
			qw422016.E().S(err.Error())
//line views/vexport/ModelDetail.html:240
		}
//line views/vexport/ModelDetail.html:240
		qw422016.N().S(`
        </div></div></div>
      </li>
`)
//line views/vexport/ModelDetail.html:243
	}
//line views/vexport/ModelDetail.html:243
	qw422016.N().S(`    </ul>
  </div>
`)
//line views/vexport/ModelDetail.html:246
}

//line views/vexport/ModelDetail.html:246
func writemodelFiles(qq422016 qtio422016.Writer, model *model.Model, fls file.Files, as *app.State, ps *cutil.PageState) {
//line views/vexport/ModelDetail.html:246
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vexport/ModelDetail.html:246
	streammodelFiles(qw422016, model, fls, as, ps)
//line views/vexport/ModelDetail.html:246
	qt422016.ReleaseWriter(qw422016)
//line views/vexport/ModelDetail.html:246
}

//line views/vexport/ModelDetail.html:246
func modelFiles(model *model.Model, fls file.Files, as *app.State, ps *cutil.PageState) string {
//line views/vexport/ModelDetail.html:246
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vexport/ModelDetail.html:246
	writemodelFiles(qb422016, model, fls, as, ps)
//line views/vexport/ModelDetail.html:246
	qs422016 := string(qb422016.B)
//line views/vexport/ModelDetail.html:246
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vexport/ModelDetail.html:246
	return qs422016
//line views/vexport/ModelDetail.html:246
}
