// Code generated by qtc from "ModelDetail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vexport/ModelDetail.html:1
package vexport

//line views/vexport/ModelDetail.html:1
import (
	"strings"

	"projectforge.dev/projectforge/app"
	"projectforge.dev/projectforge/app/controller/cutil"
	"projectforge.dev/projectforge/app/file"
	"projectforge.dev/projectforge/app/project"
	"projectforge.dev/projectforge/app/project/export/model"
	"projectforge.dev/projectforge/views/components"
	"projectforge.dev/projectforge/views/layout"
)

//line views/vexport/ModelDetail.html:13
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vexport/ModelDetail.html:13
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vexport/ModelDetail.html:13
type ModelDetail struct {
	layout.Basic
	Project *project.Project
	Model   *model.Model
	Files   file.Files
}

//line views/vexport/ModelDetail.html:20
func (p *ModelDetail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vexport/ModelDetail.html:20
	qw422016.N().S(`
`)
//line views/vexport/ModelDetail.html:21
	m := p.Model

//line views/vexport/ModelDetail.html:21
	qw422016.N().S(`  <div class="card">
    <div class="right">
      <a href="/p/`)
//line views/vexport/ModelDetail.html:24
	qw422016.E().S(p.Project.Key)
//line views/vexport/ModelDetail.html:24
	qw422016.N().S(`/export/models/`)
//line views/vexport/ModelDetail.html:24
	qw422016.E().S(p.Model.Name)
//line views/vexport/ModelDetail.html:24
	qw422016.N().S(`/edit"><button>`)
//line views/vexport/ModelDetail.html:24
	components.StreamSVGRef(qw422016, "edit", 15, 15, "icon", ps)
//line views/vexport/ModelDetail.html:24
	qw422016.N().S(`Edit</button></a>
    </div>
    <h3>`)
//line views/vexport/ModelDetail.html:26
	components.StreamSVGRefIcon(qw422016, m.IconSafe(), ps)
//line views/vexport/ModelDetail.html:26
	qw422016.E().S(m.Name)
//line views/vexport/ModelDetail.html:26
	qw422016.N().S(`</h3>
    <em>export model</em>
    `)
//line views/vexport/ModelDetail.html:28
	streammodelSummary(qw422016, p.Project.Key, m, as, ps)
//line views/vexport/ModelDetail.html:28
	qw422016.N().S(`
  </div>
  <div class="card">
    <h3>`)
//line views/vexport/ModelDetail.html:31
	components.StreamSVGRefIcon(qw422016, `first-aid`, ps)
//line views/vexport/ModelDetail.html:31
	qw422016.N().S(` Columns</h3>
    `)
//line views/vexport/ModelDetail.html:32
	streammodelColumns(qw422016, m, as, ps)
//line views/vexport/ModelDetail.html:32
	qw422016.N().S(`
  </div>
`)
//line views/vexport/ModelDetail.html:34
	if len(m.Relations) > 0 {
//line views/vexport/ModelDetail.html:34
		qw422016.N().S(`  <div class="card">
    <h3>`)
//line views/vexport/ModelDetail.html:36
		components.StreamSVGRefIcon(qw422016, `social`, ps)
//line views/vexport/ModelDetail.html:36
		qw422016.N().S(` Relations</h3>
    `)
//line views/vexport/ModelDetail.html:37
		streammodelRelations(qw422016, m, p.Project, as, ps)
//line views/vexport/ModelDetail.html:37
		qw422016.N().S(`
  </div>`)
//line views/vexport/ModelDetail.html:38
	}
//line views/vexport/ModelDetail.html:38
	if len(m.Indexes) > 0 {
//line views/vexport/ModelDetail.html:38
		qw422016.N().S(`  <div class="card">
    <h3>`)
//line views/vexport/ModelDetail.html:40
		components.StreamSVGRefIcon(qw422016, `star`, ps)
//line views/vexport/ModelDetail.html:40
		qw422016.N().S(` Indexes</h3>
    `)
//line views/vexport/ModelDetail.html:41
		streammodelIndexes(qw422016, m, as, ps)
//line views/vexport/ModelDetail.html:41
		qw422016.N().S(`
  </div>`)
//line views/vexport/ModelDetail.html:42
	}
//line views/vexport/ModelDetail.html:42
	if len(p.Files) > 0 {
//line views/vexport/ModelDetail.html:42
		qw422016.N().S(`  <div class="card">
    <h3>`)
//line views/vexport/ModelDetail.html:44
		components.StreamSVGRefIcon(qw422016, `file`, ps)
//line views/vexport/ModelDetail.html:44
		qw422016.N().S(` Exported Files</h3>
    `)
//line views/vexport/ModelDetail.html:45
		streammodelFiles(qw422016, m, p.Files, as, ps)
//line views/vexport/ModelDetail.html:45
		qw422016.N().S(`
  </div>`)
//line views/vexport/ModelDetail.html:46
	}
//line views/vexport/ModelDetail.html:47
}

//line views/vexport/ModelDetail.html:47
func (p *ModelDetail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vexport/ModelDetail.html:47
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vexport/ModelDetail.html:47
	p.StreamBody(qw422016, as, ps)
//line views/vexport/ModelDetail.html:47
	qt422016.ReleaseWriter(qw422016)
//line views/vexport/ModelDetail.html:47
}

//line views/vexport/ModelDetail.html:47
func (p *ModelDetail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vexport/ModelDetail.html:47
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vexport/ModelDetail.html:47
	p.WriteBody(qb422016, as, ps)
//line views/vexport/ModelDetail.html:47
	qs422016 := string(qb422016.B)
//line views/vexport/ModelDetail.html:47
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vexport/ModelDetail.html:47
	return qs422016
//line views/vexport/ModelDetail.html:47
}

//line views/vexport/ModelDetail.html:49
func streammodelSummary(qw422016 *qt422016.Writer, pKey string, model *model.Model, as *app.State, ps *cutil.PageState) {
//line views/vexport/ModelDetail.html:49
	qw422016.N().S(`
  <div class="overflow full-width">
    <table class="mt min-200 full-width">
      <tbody>
        <tr><th class="shrink">Name</th><td>`)
//line views/vexport/ModelDetail.html:53
	qw422016.E().S(model.Name)
//line views/vexport/ModelDetail.html:53
	qw422016.N().S(`</td></tr>
        <tr><th>Package</th><td>`)
//line views/vexport/ModelDetail.html:54
	qw422016.E().S(model.Package)
//line views/vexport/ModelDetail.html:54
	qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:55
	if len(model.Group) > 0 {
//line views/vexport/ModelDetail.html:55
		qw422016.N().S(`        <tr><th>Group</th><td>`)
//line views/vexport/ModelDetail.html:56
		qw422016.E().S(strings.Join(model.Group, "/"))
//line views/vexport/ModelDetail.html:56
		qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:57
	}
//line views/vexport/ModelDetail.html:57
	qw422016.N().S(`        <tr><th>Description</th><td>`)
//line views/vexport/ModelDetail.html:58
	qw422016.E().S(model.Description)
//line views/vexport/ModelDetail.html:58
	qw422016.N().S(`</td></tr>
        <tr>
          <th>Ordering</th>
          <td>
`)
//line views/vexport/ModelDetail.html:62
	for _, x := range model.Ordering {
//line views/vexport/ModelDetail.html:62
		qw422016.N().S(`            <div>`)
//line views/vexport/ModelDetail.html:63
		qw422016.E().S(x.String())
//line views/vexport/ModelDetail.html:63
		qw422016.N().S(`</div>
`)
//line views/vexport/ModelDetail.html:64
	}
//line views/vexport/ModelDetail.html:64
	qw422016.N().S(`          </td>
        </tr>
`)
//line views/vexport/ModelDetail.html:67
	if model.SortIndex != 0 {
//line views/vexport/ModelDetail.html:67
		qw422016.N().S(`        <tr><th>Sort Index</th><td>`)
//line views/vexport/ModelDetail.html:68
		qw422016.N().D(model.SortIndex)
//line views/vexport/ModelDetail.html:68
		qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:69
	}
//line views/vexport/ModelDetail.html:70
	if model.TitleOverride != "" {
//line views/vexport/ModelDetail.html:70
		qw422016.N().S(`        <tr><th>Title Override</th><td>`)
//line views/vexport/ModelDetail.html:71
		qw422016.E().S(model.TitleOverride)
//line views/vexport/ModelDetail.html:71
		qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:72
	}
//line views/vexport/ModelDetail.html:73
	if model.PluralOverride != "" {
//line views/vexport/ModelDetail.html:73
		qw422016.N().S(`        <tr><th>Plural Override</th><td>`)
//line views/vexport/ModelDetail.html:74
		qw422016.E().S(model.PluralOverride)
//line views/vexport/ModelDetail.html:74
		qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:75
	}
//line views/vexport/ModelDetail.html:76
	if model.ProperOverride != "" {
//line views/vexport/ModelDetail.html:76
		qw422016.N().S(`        <tr><th>Proper Override</th><td>`)
//line views/vexport/ModelDetail.html:77
		qw422016.E().S(model.ProperOverride)
//line views/vexport/ModelDetail.html:77
		qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:78
	}
//line views/vexport/ModelDetail.html:79
	if model.TableOverride != "" {
//line views/vexport/ModelDetail.html:79
		qw422016.N().S(`        <tr><th>Table Override</th><td>`)
//line views/vexport/ModelDetail.html:80
		qw422016.E().S(model.TableOverride)
//line views/vexport/ModelDetail.html:80
		qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:81
	}
//line views/vexport/ModelDetail.html:82
	if model.RouteOverride != "" {
//line views/vexport/ModelDetail.html:82
		qw422016.N().S(`        <tr><th>Route Override</th><td>`)
//line views/vexport/ModelDetail.html:83
		qw422016.E().S(model.RouteOverride)
//line views/vexport/ModelDetail.html:83
		qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:84
	}
//line views/vexport/ModelDetail.html:85
	if len(model.Tags) > 0 {
//line views/vexport/ModelDetail.html:85
		qw422016.N().S(`        <tr><th>Tags</th><td>`)
//line views/vexport/ModelDetail.html:86
		qw422016.E().S(strings.Join(model.Tags, ", "))
//line views/vexport/ModelDetail.html:86
		qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:87
	}
//line views/vexport/ModelDetail.html:88
	if model.View != "" {
//line views/vexport/ModelDetail.html:88
		qw422016.N().S(`        <tr><th>View</th><td>`)
//line views/vexport/ModelDetail.html:89
		qw422016.E().S(model.View)
//line views/vexport/ModelDetail.html:89
		qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:90
	}
//line views/vexport/ModelDetail.html:91
	if len(model.Search) > 0 {
//line views/vexport/ModelDetail.html:91
		qw422016.N().S(`        <tr><th>Search</th><td>`)
//line views/vexport/ModelDetail.html:92
		qw422016.E().S(strings.Join(model.Search, ", "))
//line views/vexport/ModelDetail.html:92
		qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:93
	}
//line views/vexport/ModelDetail.html:94
	if len(model.SeedData) > 0 {
//line views/vexport/ModelDetail.html:94
		qw422016.N().S(`        <tr><th>Seed Data</th><td><a href="/p/`)
//line views/vexport/ModelDetail.html:95
		qw422016.E().S(pKey)
//line views/vexport/ModelDetail.html:95
		qw422016.N().S(`/export/models/`)
//line views/vexport/ModelDetail.html:95
		qw422016.E().S(model.Name)
//line views/vexport/ModelDetail.html:95
		qw422016.N().S(`/seeddata">`)
//line views/vexport/ModelDetail.html:95
		qw422016.N().D(len(model.SeedData))
//line views/vexport/ModelDetail.html:95
		qw422016.N().S(` rows</a></td></tr>
`)
//line views/vexport/ModelDetail.html:96
	}
//line views/vexport/ModelDetail.html:97
	if len(model.Config) > 0 {
//line views/vexport/ModelDetail.html:97
		qw422016.N().S(`        <tr><th>Config</th><td>`)
//line views/vexport/ModelDetail.html:98
		components.StreamJSON(qw422016, model.Config)
//line views/vexport/ModelDetail.html:98
		qw422016.N().S(`</td></tr>
`)
//line views/vexport/ModelDetail.html:99
	}
//line views/vexport/ModelDetail.html:99
	qw422016.N().S(`      </tbody>
    </table>
  </div>
`)
//line views/vexport/ModelDetail.html:103
}

//line views/vexport/ModelDetail.html:103
func writemodelSummary(qq422016 qtio422016.Writer, pKey string, model *model.Model, as *app.State, ps *cutil.PageState) {
//line views/vexport/ModelDetail.html:103
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vexport/ModelDetail.html:103
	streammodelSummary(qw422016, pKey, model, as, ps)
//line views/vexport/ModelDetail.html:103
	qt422016.ReleaseWriter(qw422016)
//line views/vexport/ModelDetail.html:103
}

//line views/vexport/ModelDetail.html:103
func modelSummary(pKey string, model *model.Model, as *app.State, ps *cutil.PageState) string {
//line views/vexport/ModelDetail.html:103
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vexport/ModelDetail.html:103
	writemodelSummary(qb422016, pKey, model, as, ps)
//line views/vexport/ModelDetail.html:103
	qs422016 := string(qb422016.B)
//line views/vexport/ModelDetail.html:103
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vexport/ModelDetail.html:103
	return qs422016
//line views/vexport/ModelDetail.html:103
}

//line views/vexport/ModelDetail.html:105
func streammodelColumns(qw422016 *qt422016.Writer, model *model.Model, as *app.State, ps *cutil.PageState) {
//line views/vexport/ModelDetail.html:105
	qw422016.N().S(`
`)
//line views/vexport/ModelDetail.html:106
	if len(model.Columns) == 0 {
//line views/vexport/ModelDetail.html:106
		qw422016.N().S(`  <p><em>no columns</em></p>
`)
//line views/vexport/ModelDetail.html:108
	} else {
//line views/vexport/ModelDetail.html:108
		qw422016.N().S(`  <div class="overflow full-width">
    <table class="mt min-200 full-width">
      <thead>
        <tr>
          <th class="shrink">Name</th>
          <th>Type</th>
          <th>Format</th>
          <th>Example</th>
          <th>JSON</th>
          <th>Validation</th>
          <th>Indexed</th>
          <th>Unique</th>
          <th>Tags</th>
        </tr>
      </thead>
      <tbody>
`)
//line views/vexport/ModelDetail.html:125
		for _, col := range model.Columns {
//line views/vexport/ModelDetail.html:125
			qw422016.N().S(`        <tr>
          <td>`)
//line views/vexport/ModelDetail.html:127
			qw422016.E().S(col.Name)
//line views/vexport/ModelDetail.html:127
			qw422016.N().S(`</td>
          <td>`)
//line views/vexport/ModelDetail.html:128
			qw422016.E().S(col.Type.String())
//line views/vexport/ModelDetail.html:128
			qw422016.N().S(`</td>
          <td>`)
//line views/vexport/ModelDetail.html:129
			qw422016.E().S(col.Format)
//line views/vexport/ModelDetail.html:129
			qw422016.N().S(`</td>
          <td>`)
//line views/vexport/ModelDetail.html:130
			qw422016.E().S(col.Example)
//line views/vexport/ModelDetail.html:130
			qw422016.N().S(`</td>
          <td>`)
//line views/vexport/ModelDetail.html:131
			qw422016.E().S(col.JSON)
//line views/vexport/ModelDetail.html:131
			qw422016.N().S(`</td>
          <td>`)
//line views/vexport/ModelDetail.html:132
			qw422016.E().S(col.Validation)
//line views/vexport/ModelDetail.html:132
			qw422016.N().S(`</td>
          <td>`)
//line views/vexport/ModelDetail.html:133
			if col.Indexed || model.Relations.ContainsSource(col.Name) {
//line views/vexport/ModelDetail.html:133
				components.StreamSVGRef(qw422016, "check", 15, 15, "icon", ps)
//line views/vexport/ModelDetail.html:133
			}
//line views/vexport/ModelDetail.html:133
			qw422016.N().S(`</td>
          <td>`)
//line views/vexport/ModelDetail.html:134
			if col.HasTag("unique") {
//line views/vexport/ModelDetail.html:134
				components.StreamSVGRef(qw422016, "check", 15, 15, "icon", ps)
//line views/vexport/ModelDetail.html:134
			}
//line views/vexport/ModelDetail.html:134
			qw422016.N().S(`</td>
          <td>`)
//line views/vexport/ModelDetail.html:135
			qw422016.E().S(strings.Join(col.Tags, ", "))
//line views/vexport/ModelDetail.html:135
			qw422016.N().S(`</td>
        </tr>
`)
//line views/vexport/ModelDetail.html:137
		}
//line views/vexport/ModelDetail.html:137
		qw422016.N().S(`      </tbody>
    </table>
  </div>
`)
//line views/vexport/ModelDetail.html:141
	}
//line views/vexport/ModelDetail.html:142
}

//line views/vexport/ModelDetail.html:142
func writemodelColumns(qq422016 qtio422016.Writer, model *model.Model, as *app.State, ps *cutil.PageState) {
//line views/vexport/ModelDetail.html:142
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vexport/ModelDetail.html:142
	streammodelColumns(qw422016, model, as, ps)
//line views/vexport/ModelDetail.html:142
	qt422016.ReleaseWriter(qw422016)
//line views/vexport/ModelDetail.html:142
}

//line views/vexport/ModelDetail.html:142
func modelColumns(model *model.Model, as *app.State, ps *cutil.PageState) string {
//line views/vexport/ModelDetail.html:142
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vexport/ModelDetail.html:142
	writemodelColumns(qb422016, model, as, ps)
//line views/vexport/ModelDetail.html:142
	qs422016 := string(qb422016.B)
//line views/vexport/ModelDetail.html:142
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vexport/ModelDetail.html:142
	return qs422016
//line views/vexport/ModelDetail.html:142
}

//line views/vexport/ModelDetail.html:144
func streammodelRelations(qw422016 *qt422016.Writer, model *model.Model, prj *project.Project, as *app.State, ps *cutil.PageState) {
//line views/vexport/ModelDetail.html:144
	qw422016.N().S(`
  <div class="overflow full-width">
    <table class="mt min-200 full-width">
      <thead>
        <tr>
          <th class="shrink">Name</th>
          <th>Source</th>
          <th>Table</th>
          <th>Target</th>
        </tr>
      </thead>
      <tbody>
`)
//line views/vexport/ModelDetail.html:156
	for _, rel := range model.Relations {
//line views/vexport/ModelDetail.html:156
		qw422016.N().S(`        <tr>
          <td>`)
//line views/vexport/ModelDetail.html:158
		qw422016.E().S(rel.Name)
//line views/vexport/ModelDetail.html:158
		qw422016.N().S(`</td>
          <td>`)
//line views/vexport/ModelDetail.html:159
		qw422016.E().S(strings.Join(rel.Src, ", "))
//line views/vexport/ModelDetail.html:159
		qw422016.N().S(`</td>
          <td><a href="`)
//line views/vexport/ModelDetail.html:160
		qw422016.E().S(prj.WebPath())
//line views/vexport/ModelDetail.html:160
		qw422016.N().S(`/export/models/`)
//line views/vexport/ModelDetail.html:160
		qw422016.E().S(rel.Table)
//line views/vexport/ModelDetail.html:160
		qw422016.N().S(`">`)
//line views/vexport/ModelDetail.html:160
		qw422016.E().S(rel.Table)
//line views/vexport/ModelDetail.html:160
		qw422016.N().S(`</a></td>
          <td>`)
//line views/vexport/ModelDetail.html:161
		qw422016.E().S(strings.Join(rel.Tgt, ", "))
//line views/vexport/ModelDetail.html:161
		qw422016.N().S(`</td>
        </tr>
`)
//line views/vexport/ModelDetail.html:163
	}
//line views/vexport/ModelDetail.html:163
	qw422016.N().S(`      </tbody>
    </table>
  </div>
`)
//line views/vexport/ModelDetail.html:167
}

//line views/vexport/ModelDetail.html:167
func writemodelRelations(qq422016 qtio422016.Writer, model *model.Model, prj *project.Project, as *app.State, ps *cutil.PageState) {
//line views/vexport/ModelDetail.html:167
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vexport/ModelDetail.html:167
	streammodelRelations(qw422016, model, prj, as, ps)
//line views/vexport/ModelDetail.html:167
	qt422016.ReleaseWriter(qw422016)
//line views/vexport/ModelDetail.html:167
}

//line views/vexport/ModelDetail.html:167
func modelRelations(model *model.Model, prj *project.Project, as *app.State, ps *cutil.PageState) string {
//line views/vexport/ModelDetail.html:167
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vexport/ModelDetail.html:167
	writemodelRelations(qb422016, model, prj, as, ps)
//line views/vexport/ModelDetail.html:167
	qs422016 := string(qb422016.B)
//line views/vexport/ModelDetail.html:167
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vexport/ModelDetail.html:167
	return qs422016
//line views/vexport/ModelDetail.html:167
}

//line views/vexport/ModelDetail.html:169
func streammodelIndexes(qw422016 *qt422016.Writer, model *model.Model, as *app.State, ps *cutil.PageState) {
//line views/vexport/ModelDetail.html:169
	qw422016.N().S(`
  <div class="overflow full-width">
    <table class="mt min-200 full-width">
      <thead>
        <tr>
          <th class="shrink">Name</th>
          <th>Declaration</th>
        </tr>
      </thead>
      <tbody>
`)
//line views/vexport/ModelDetail.html:179
	for _, idx := range model.Indexes {
//line views/vexport/ModelDetail.html:179
		qw422016.N().S(`        <tr>
          <td>`)
//line views/vexport/ModelDetail.html:181
		qw422016.E().S(idx.Name)
//line views/vexport/ModelDetail.html:181
		qw422016.N().S(`</td>
          <td>`)
//line views/vexport/ModelDetail.html:182
		qw422016.E().S(idx.Decl)
//line views/vexport/ModelDetail.html:182
		qw422016.N().S(`</td>
        </tr>
`)
//line views/vexport/ModelDetail.html:184
	}
//line views/vexport/ModelDetail.html:184
	qw422016.N().S(`      </tbody>
    </table>
  </div>
`)
//line views/vexport/ModelDetail.html:188
}

//line views/vexport/ModelDetail.html:188
func writemodelIndexes(qq422016 qtio422016.Writer, model *model.Model, as *app.State, ps *cutil.PageState) {
//line views/vexport/ModelDetail.html:188
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vexport/ModelDetail.html:188
	streammodelIndexes(qw422016, model, as, ps)
//line views/vexport/ModelDetail.html:188
	qt422016.ReleaseWriter(qw422016)
//line views/vexport/ModelDetail.html:188
}

//line views/vexport/ModelDetail.html:188
func modelIndexes(model *model.Model, as *app.State, ps *cutil.PageState) string {
//line views/vexport/ModelDetail.html:188
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vexport/ModelDetail.html:188
	writemodelIndexes(qb422016, model, as, ps)
//line views/vexport/ModelDetail.html:188
	qs422016 := string(qb422016.B)
//line views/vexport/ModelDetail.html:188
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vexport/ModelDetail.html:188
	return qs422016
//line views/vexport/ModelDetail.html:188
}

//line views/vexport/ModelDetail.html:190
func streammodelFiles(qw422016 *qt422016.Writer, model *model.Model, fls file.Files, as *app.State, ps *cutil.PageState) {
//line views/vexport/ModelDetail.html:190
	qw422016.N().S(`
  <div class="mt">
    <ul class="accordion">
`)
//line views/vexport/ModelDetail.html:193
	for _, f := range fls {
//line views/vexport/ModelDetail.html:193
		qw422016.N().S(`      <li>
        <input id="accordion-`)
//line views/vexport/ModelDetail.html:195
		qw422016.E().S(f.FullPath())
//line views/vexport/ModelDetail.html:195
		qw422016.N().S(`" type="checkbox" hidden />
        <label for="accordion-`)
//line views/vexport/ModelDetail.html:196
		qw422016.E().S(f.FullPath())
//line views/vexport/ModelDetail.html:196
		qw422016.N().S(`">`)
//line views/vexport/ModelDetail.html:196
		components.StreamExpandCollapse(qw422016, 3, ps)
//line views/vexport/ModelDetail.html:196
		qw422016.N().S(` `)
//line views/vexport/ModelDetail.html:196
		qw422016.E().S(f.FullPath())
//line views/vexport/ModelDetail.html:196
		qw422016.N().S(`</label>
        <div class="bd"><div><div>
`)
//line views/vexport/ModelDetail.html:198
		out, err := cutil.FormatLang(f.Content, f.Ext())

//line views/vexport/ModelDetail.html:198
		qw422016.N().S(`          `)
//line views/vexport/ModelDetail.html:199
		if err == nil {
//line views/vexport/ModelDetail.html:199
			qw422016.N().S(out)
//line views/vexport/ModelDetail.html:199
		} else {
//line views/vexport/ModelDetail.html:199
			qw422016.E().S(err.Error())
//line views/vexport/ModelDetail.html:199
		}
//line views/vexport/ModelDetail.html:199
		qw422016.N().S(`
        </div></div></div>
      </li>
`)
//line views/vexport/ModelDetail.html:202
	}
//line views/vexport/ModelDetail.html:202
	qw422016.N().S(`    </ul>
  </div>
`)
//line views/vexport/ModelDetail.html:205
}

//line views/vexport/ModelDetail.html:205
func writemodelFiles(qq422016 qtio422016.Writer, model *model.Model, fls file.Files, as *app.State, ps *cutil.PageState) {
//line views/vexport/ModelDetail.html:205
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vexport/ModelDetail.html:205
	streammodelFiles(qw422016, model, fls, as, ps)
//line views/vexport/ModelDetail.html:205
	qt422016.ReleaseWriter(qw422016)
//line views/vexport/ModelDetail.html:205
}

//line views/vexport/ModelDetail.html:205
func modelFiles(model *model.Model, fls file.Files, as *app.State, ps *cutil.PageState) string {
//line views/vexport/ModelDetail.html:205
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vexport/ModelDetail.html:205
	writemodelFiles(qb422016, model, fls, as, ps)
//line views/vexport/ModelDetail.html:205
	qs422016 := string(qb422016.B)
//line views/vexport/ModelDetail.html:205
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vexport/ModelDetail.html:205
	return qs422016
//line views/vexport/ModelDetail.html:205
}
