// Code generated by qtc from "Sitemap.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vadmin/Sitemap.html:2
package vadmin

//line views/vadmin/Sitemap.html:2
import (
	"slices"

	"projectforge.dev/projectforge/app"
	"projectforge.dev/projectforge/app/controller/cmenu"
	"projectforge.dev/projectforge/app/controller/cutil"
	"projectforge.dev/projectforge/app/lib/menu"
	"projectforge.dev/projectforge/views/components"
	"projectforge.dev/projectforge/views/layout"
)

//line views/vadmin/Sitemap.html:13
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vadmin/Sitemap.html:13
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vadmin/Sitemap.html:13
type Sitemap struct {
	layout.Basic
}

//line views/vadmin/Sitemap.html:17
func (p *Sitemap) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vadmin/Sitemap.html:17
	qw422016.N().S(`
  <div class="card">
    <h3>`)
//line views/vadmin/Sitemap.html:19
	components.StreamSVGIcon(qw422016, `star`, ps)
//line views/vadmin/Sitemap.html:19
	qw422016.N().S(`Sitemap</h3>
    <div class="mt">
      `)
//line views/vadmin/Sitemap.html:21
	StreamSitemapDetail(qw422016, ps.Menu, 1, ps)
//line views/vadmin/Sitemap.html:21
	qw422016.N().S(`
    </div>
  </div>
`)
//line views/vadmin/Sitemap.html:24
}

//line views/vadmin/Sitemap.html:24
func (p *Sitemap) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vadmin/Sitemap.html:24
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vadmin/Sitemap.html:24
	p.StreamBody(qw422016, as, ps)
//line views/vadmin/Sitemap.html:24
	qt422016.ReleaseWriter(qw422016)
//line views/vadmin/Sitemap.html:24
}

//line views/vadmin/Sitemap.html:24
func (p *Sitemap) Body(as *app.State, ps *cutil.PageState) string {
//line views/vadmin/Sitemap.html:24
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vadmin/Sitemap.html:24
	p.WriteBody(qb422016, as, ps)
//line views/vadmin/Sitemap.html:24
	qs422016 := string(qb422016.B)
//line views/vadmin/Sitemap.html:24
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vadmin/Sitemap.html:24
	return qs422016
//line views/vadmin/Sitemap.html:24
}

//line views/vadmin/Sitemap.html:26
func StreamSitemapDetail(qw422016 *qt422016.Writer, m menu.Items, indent int, ps *cutil.PageState) {
//line views/vadmin/Sitemap.html:27
	components.StreamIndent(qw422016, true, 1)
//line views/vadmin/Sitemap.html:27
	qw422016.N().S(`<div class="mt">`)
//line views/vadmin/Sitemap.html:29
	components.StreamIndent(qw422016, true, 2)
//line views/vadmin/Sitemap.html:29
	qw422016.N().S(`<ul class="level-0">`)
//line views/vadmin/Sitemap.html:31
	for _, i := range m {
//line views/vadmin/Sitemap.html:32
		if i.Key != "" {
//line views/vadmin/Sitemap.html:33
			streamsitemapItemDetail(qw422016, i, []string{}, ps.Breadcrumbs, 3, ps)
//line views/vadmin/Sitemap.html:34
		}
//line views/vadmin/Sitemap.html:35
	}
//line views/vadmin/Sitemap.html:36
	components.StreamIndent(qw422016, true, 2)
//line views/vadmin/Sitemap.html:36
	qw422016.N().S(`</ul>`)
//line views/vadmin/Sitemap.html:38
	components.StreamIndent(qw422016, true, 1)
//line views/vadmin/Sitemap.html:38
	qw422016.N().S(`</div>`)
//line views/vadmin/Sitemap.html:40
}

//line views/vadmin/Sitemap.html:40
func WriteSitemapDetail(qq422016 qtio422016.Writer, m menu.Items, indent int, ps *cutil.PageState) {
//line views/vadmin/Sitemap.html:40
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vadmin/Sitemap.html:40
	StreamSitemapDetail(qw422016, m, indent, ps)
//line views/vadmin/Sitemap.html:40
	qt422016.ReleaseWriter(qw422016)
//line views/vadmin/Sitemap.html:40
}

//line views/vadmin/Sitemap.html:40
func SitemapDetail(m menu.Items, indent int, ps *cutil.PageState) string {
//line views/vadmin/Sitemap.html:40
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vadmin/Sitemap.html:40
	WriteSitemapDetail(qb422016, m, indent, ps)
//line views/vadmin/Sitemap.html:40
	qs422016 := string(qb422016.B)
//line views/vadmin/Sitemap.html:40
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vadmin/Sitemap.html:40
	return qs422016
//line views/vadmin/Sitemap.html:40
}

//line views/vadmin/Sitemap.html:42
func streamsitemapItemDetail(qw422016 *qt422016.Writer, i *menu.Item, path []string, breadcrumbs cmenu.Breadcrumbs, indent int, ps *cutil.PageState) {
//line views/vadmin/Sitemap.html:43
	components.StreamIndent(qw422016, true, indent)
//line views/vadmin/Sitemap.html:43
	qw422016.N().S(`<li><div class="mts">`)
//line views/vadmin/Sitemap.html:46
	components.StreamIndent(qw422016, true, indent+1)
//line views/vadmin/Sitemap.html:46
	qw422016.N().S(`<a href="`)
//line views/vadmin/Sitemap.html:47
	qw422016.E().S(i.Route)
//line views/vadmin/Sitemap.html:47
	qw422016.N().S(`" title="`)
//line views/vadmin/Sitemap.html:47
	qw422016.E().S(i.Desc())
//line views/vadmin/Sitemap.html:47
	qw422016.N().S(`">`)
//line views/vadmin/Sitemap.html:48
	if i.Icon != "" {
//line views/vadmin/Sitemap.html:49
		components.StreamSVGRef(qw422016, i.Icon, 16, 16, "icon", ps)
//line views/vadmin/Sitemap.html:50
	}
//line views/vadmin/Sitemap.html:51
	qw422016.E().S(i.Title)
//line views/vadmin/Sitemap.html:51
	qw422016.N().S(`</a><div><em>`)
//line views/vadmin/Sitemap.html:53
	qw422016.E().S(i.Desc())
//line views/vadmin/Sitemap.html:53
	qw422016.N().S(`</em></div>`)
//line views/vadmin/Sitemap.html:54
	if len(i.Children) > 0 {
//line views/vadmin/Sitemap.html:54
		qw422016.N().S(`<ul class="level-`)
//line views/vadmin/Sitemap.html:55
		qw422016.N().D(len(path))
//line views/vadmin/Sitemap.html:55
		qw422016.N().S(`">`)
//line views/vadmin/Sitemap.html:56
		for _, kid := range i.Children {
//line views/vadmin/Sitemap.html:57
			if kid.Key != "" {
//line views/vadmin/Sitemap.html:58
				streamsitemapItemDetail(qw422016, kid, append(slices.Clone(path), i.Key), breadcrumbs, indent+2, ps)
//line views/vadmin/Sitemap.html:59
			}
//line views/vadmin/Sitemap.html:60
		}
//line views/vadmin/Sitemap.html:60
		qw422016.N().S(`</ul>`)
//line views/vadmin/Sitemap.html:62
	}
//line views/vadmin/Sitemap.html:62
	qw422016.N().S(`</div>`)
//line views/vadmin/Sitemap.html:64
	components.StreamIndent(qw422016, true, indent)
//line views/vadmin/Sitemap.html:64
	qw422016.N().S(`</li>`)
//line views/vadmin/Sitemap.html:66
}

//line views/vadmin/Sitemap.html:66
func writesitemapItemDetail(qq422016 qtio422016.Writer, i *menu.Item, path []string, breadcrumbs cmenu.Breadcrumbs, indent int, ps *cutil.PageState) {
//line views/vadmin/Sitemap.html:66
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vadmin/Sitemap.html:66
	streamsitemapItemDetail(qw422016, i, path, breadcrumbs, indent, ps)
//line views/vadmin/Sitemap.html:66
	qt422016.ReleaseWriter(qw422016)
//line views/vadmin/Sitemap.html:66
}

//line views/vadmin/Sitemap.html:66
func sitemapItemDetail(i *menu.Item, path []string, breadcrumbs cmenu.Breadcrumbs, indent int, ps *cutil.PageState) string {
//line views/vadmin/Sitemap.html:66
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vadmin/Sitemap.html:66
	writesitemapItemDetail(qb422016, i, path, breadcrumbs, indent, ps)
//line views/vadmin/Sitemap.html:66
	qs422016 := string(qb422016.B)
//line views/vadmin/Sitemap.html:66
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vadmin/Sitemap.html:66
	return qs422016
//line views/vadmin/Sitemap.html:66
}
