// Code generated by qtc from "Model.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vjsonschema/Model.html:1
package vjsonschema

//line views/vjsonschema/Model.html:1
import (
	"projectforge.dev/projectforge/app"
	"projectforge.dev/projectforge/app/controller/cutil"
	"projectforge.dev/projectforge/app/lib/jsonschema"
	"projectforge.dev/projectforge/app/lib/metamodel/model"
	"projectforge.dev/projectforge/app/util"
	"projectforge.dev/projectforge/views/components"
	"projectforge.dev/projectforge/views/layout"
)

//line views/vjsonschema/Model.html:11
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vjsonschema/Model.html:11
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vjsonschema/Model.html:11
type ModelDetail struct {
	layout.Basic
	BaseURL    string
	Model      *model.Model
	Collection *jsonschema.Collection
	Result     *model.Model
}

//line views/vjsonschema/Model.html:19
func (p *ModelDetail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vjsonschema/Model.html:19
	qw422016.N().S(`
`)
//line views/vjsonschema/Model.html:20
	x := p.Model

//line views/vjsonschema/Model.html:20
	qw422016.N().S(`  <div class="card">
`)
//line views/vjsonschema/Model.html:22
	sch := p.Collection.GetSchema(x.ID())

//line views/vjsonschema/Model.html:23
	df := util.DiffObjects(x, p.Result)

//line views/vjsonschema/Model.html:24
	if len(df) > 0 {
//line views/vjsonschema/Model.html:24
		qw422016.N().S(`    <div class="right">
      `)
//line views/vjsonschema/Model.html:26
		qw422016.E().S(util.StringPlural(len(df), "difference"))
//line views/vjsonschema/Model.html:26
		qw422016.N().S(`
    </div>
`)
//line views/vjsonschema/Model.html:28
	}
//line views/vjsonschema/Model.html:28
	qw422016.N().S(`    <h3>`)
//line views/vjsonschema/Model.html:29
	components.StreamSVGIcon(qw422016, `table`, ps)
//line views/vjsonschema/Model.html:29
	qw422016.N().S(` [`)
//line views/vjsonschema/Model.html:29
	qw422016.E().S(x.Name)
//line views/vjsonschema/Model.html:29
	qw422016.N().S(`] JSON Schema</h3>
    `)
//line views/vjsonschema/Model.html:30
	StreamRenderModel(qw422016, p.BaseURL, x, sch, p.Result, df, ps)
//line views/vjsonschema/Model.html:30
	qw422016.N().S(`
  </div>
`)
//line views/vjsonschema/Model.html:32
}

//line views/vjsonschema/Model.html:32
func (p *ModelDetail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vjsonschema/Model.html:32
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vjsonschema/Model.html:32
	p.StreamBody(qw422016, as, ps)
//line views/vjsonschema/Model.html:32
	qt422016.ReleaseWriter(qw422016)
//line views/vjsonschema/Model.html:32
}

//line views/vjsonschema/Model.html:32
func (p *ModelDetail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vjsonschema/Model.html:32
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vjsonschema/Model.html:32
	p.WriteBody(qb422016, as, ps)
//line views/vjsonschema/Model.html:32
	qs422016 := string(qb422016.B)
//line views/vjsonschema/Model.html:32
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vjsonschema/Model.html:32
	return qs422016
//line views/vjsonschema/Model.html:32
}

//line views/vjsonschema/Model.html:34
func StreamRenderModel(qw422016 *qt422016.Writer, baseURL string, x *model.Model, sch *jsonschema.Schema, result *model.Model, df util.Diffs, ps *cutil.PageState) {
//line views/vjsonschema/Model.html:34
	qw422016.N().S(`
  <div class="flex">
    <div class="flex-item">
      <a href="`)
//line views/vjsonschema/Model.html:37
	qw422016.E().S(baseURL)
//line views/vjsonschema/Model.html:37
	qw422016.N().S(`/`)
//line views/vjsonschema/Model.html:37
	qw422016.E().S(x.Name)
//line views/vjsonschema/Model.html:37
	qw422016.N().S(`"><strong>Original</strong></a>
      <pre class="mt">`)
//line views/vjsonschema/Model.html:38
	qw422016.E().S(util.ToJSON(x))
//line views/vjsonschema/Model.html:38
	qw422016.N().S(`</pre>
    </div>
    <div class="flex-item">
      <strong>Result</strong>
      <pre class="mt">`)
//line views/vjsonschema/Model.html:42
	qw422016.E().S(util.ToJSON(result))
//line views/vjsonschema/Model.html:42
	qw422016.N().S(`</pre>
    </div>
  </div>
  <div class="flex">
    <div class="flex-item">
      <strong>Schema</strong>
      <pre class="mt">`)
//line views/vjsonschema/Model.html:48
	qw422016.E().S(util.ToJSON(sch))
//line views/vjsonschema/Model.html:48
	qw422016.N().S(`</pre>
    </div>
    <div class="flex-item">
      <strong>Diff</strong>
      <pre class="mt">`)
//line views/vjsonschema/Model.html:52
	qw422016.E().S(util.ToJSON(df))
//line views/vjsonschema/Model.html:52
	qw422016.N().S(`</pre>
    </div>
  </div>
`)
//line views/vjsonschema/Model.html:55
}

//line views/vjsonschema/Model.html:55
func WriteRenderModel(qq422016 qtio422016.Writer, baseURL string, x *model.Model, sch *jsonschema.Schema, result *model.Model, df util.Diffs, ps *cutil.PageState) {
//line views/vjsonschema/Model.html:55
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vjsonschema/Model.html:55
	StreamRenderModel(qw422016, baseURL, x, sch, result, df, ps)
//line views/vjsonschema/Model.html:55
	qt422016.ReleaseWriter(qw422016)
//line views/vjsonschema/Model.html:55
}

//line views/vjsonschema/Model.html:55
func RenderModel(baseURL string, x *model.Model, sch *jsonschema.Schema, result *model.Model, df util.Diffs, ps *cutil.PageState) string {
//line views/vjsonschema/Model.html:55
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vjsonschema/Model.html:55
	WriteRenderModel(qb422016, baseURL, x, sch, result, df, ps)
//line views/vjsonschema/Model.html:55
	qs422016 := string(qb422016.B)
//line views/vjsonschema/Model.html:55
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vjsonschema/Model.html:55
	return qs422016
//line views/vjsonschema/Model.html:55
}
